package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContpotentialrel generated by hbm2java
 */
public class VtigerContpotentialrel implements java.io.Serializable {

	private VtigerContpotentialrelId id;

	public VtigerContpotentialrel() {
	}

	public VtigerContpotentialrel(VtigerContpotentialrelId id) {
		this.id = id;
	}

	public VtigerContpotentialrelId getId() {
		return this.id;
	}

	public void setId(VtigerContpotentialrelId id) {
		this.id = id;
	}

}
