package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInventoryproductrel generated by hbm2java
 */
public class VtigerInventoryproductrel implements java.io.Serializable {

	private int lineitemId;
	private Integer id;
	private Integer productid;
	private Integer sequenceNo;
	private Integer qtyinstock;
	private Integer quantity;
	private String listprice;
	private String discountPercent;
	private String discountAmount;
	private String comment;
	private String description;
	private int incrementondel;
	private String tax1;
	private String tax2;
	private String tax3;
	private String vat;
	private String taxamount;
	private String withcform;
	private String cstwithcformPer;
	private String cstwithcformAmt;
	private String cstwithoutcformPer;
	private String cstwithoutcformAmt;
	private String service;
	private String netprice;
	private String tax4;
	private String tax5;
	private String tax6;

	public VtigerInventoryproductrel() {
	}

	public VtigerInventoryproductrel(int lineitemId, int incrementondel) {
		this.lineitemId = lineitemId;
		this.incrementondel = incrementondel;
	}

	public VtigerInventoryproductrel(int lineitemId, Integer id, Integer productid,
				Integer sequenceNo, Integer qtyinstock, Integer quantity, String listprice,
				String discountPercent, String discountAmount, String comment, String description,
				int incrementondel, String tax1, String tax2, String tax3, String vat,
				String taxamount, String withcform, String cstwithcformPer, String cstwithcformAmt,
				String cstwithoutcformPer, String cstwithoutcformAmt, String service,
				String netprice, String tax4, String tax5, String tax6) {
		this.lineitemId = lineitemId;
		this.id = id;
		this.productid = productid;
		this.sequenceNo = sequenceNo;
		this.qtyinstock = qtyinstock;
		this.quantity = quantity;
		this.listprice = listprice;
		this.discountPercent = discountPercent;
		this.discountAmount = discountAmount;
		this.comment = comment;
		this.description = description;
		this.incrementondel = incrementondel;
		this.tax1 = tax1;
		this.tax2 = tax2;
		this.tax3 = tax3;
		this.vat = vat;
		this.taxamount = taxamount;
		this.withcform = withcform;
		this.cstwithcformPer = cstwithcformPer;
		this.cstwithcformAmt = cstwithcformAmt;
		this.cstwithoutcformPer = cstwithoutcformPer;
		this.cstwithoutcformAmt = cstwithoutcformAmt;
		this.service = service;
		this.netprice = netprice;
		this.tax4 = tax4;
		this.tax5 = tax5;
		this.tax6 = tax6;
	}

	public VtigerInventoryproductrel(int new_crmid, int productid, String sequence_no,
				String quantity, String listprice, String discount_amount, int incrementondel,
				int lineitem_id, String vat, String taxamount, String netprice) {

		this.id = new_crmid;
		this.productid = productid;
		this.sequenceNo = Integer.parseInt(sequence_no);
		this.quantity = Integer.parseInt(quantity);
		this.listprice = listprice;
		this.discountAmount = discount_amount;
		this.incrementondel = incrementondel;
		this.lineitemId = lineitem_id;
		this.vat = vat;
		this.taxamount = taxamount;
		this.netprice = netprice;
	}

	public int getLineitemId() {
		return this.lineitemId;
	}

	public void setLineitemId(int lineitemId) {
		this.lineitemId = lineitemId;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getProductid() {
		return this.productid;
	}

	public void setProductid(Integer productid) {
		this.productid = productid;
	}

	public Integer getSequenceNo() {
		return this.sequenceNo;
	}

	public void setSequenceNo(Integer sequenceNo) {
		this.sequenceNo = sequenceNo;
	}

	public Integer getQtyinstock() {
		return this.qtyinstock;
	}

	public void setQtyinstock(Integer qtyinstock) {
		this.qtyinstock = qtyinstock;
	}

	public Integer getQuantity() {
		return this.quantity;
	}

	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	public String getListprice() {
		return this.listprice;
	}

	public void setListprice(String listprice) {
		this.listprice = listprice;
	}

	public String getDiscountPercent() {
		return this.discountPercent;
	}

	public void setDiscountPercent(String discountPercent) {
		this.discountPercent = discountPercent;
	}

	public String getDiscountAmount() {
		return this.discountAmount;
	}

	public void setDiscountAmount(String discountAmount) {
		this.discountAmount = discountAmount;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public int getIncrementondel() {
		return this.incrementondel;
	}

	public void setIncrementondel(int incrementondel) {
		this.incrementondel = incrementondel;
	}

	public String getTax1() {
		return this.tax1;
	}

	public void setTax1(String tax1) {
		this.tax1 = tax1;
	}

	public String getTax2() {
		return this.tax2;
	}

	public void setTax2(String tax2) {
		this.tax2 = tax2;
	}

	public String getTax3() {
		return this.tax3;
	}

	public void setTax3(String tax3) {
		this.tax3 = tax3;
	}

	public String getVat() {
		return this.vat;
	}

	public void setVat(String vat) {
		this.vat = vat;
	}

	public String getTaxamount() {
		return this.taxamount;
	}

	public void setTaxamount(String taxamount) {
		this.taxamount = taxamount;
	}

	public String getWithcform() {
		return this.withcform;
	}

	public void setWithcform(String withcform) {
		this.withcform = withcform;
	}

	public String getCstwithcformPer() {
		return this.cstwithcformPer;
	}

	public void setCstwithcformPer(String cstwithcformPer) {
		this.cstwithcformPer = cstwithcformPer;
	}

	public String getCstwithcformAmt() {
		return this.cstwithcformAmt;
	}

	public void setCstwithcformAmt(String cstwithcformAmt) {
		this.cstwithcformAmt = cstwithcformAmt;
	}

	public String getCstwithoutcformPer() {
		return this.cstwithoutcformPer;
	}

	public void setCstwithoutcformPer(String cstwithoutcformPer) {
		this.cstwithoutcformPer = cstwithoutcformPer;
	}

	public String getCstwithoutcformAmt() {
		return this.cstwithoutcformAmt;
	}

	public void setCstwithoutcformAmt(String cstwithoutcformAmt) {
		this.cstwithoutcformAmt = cstwithoutcformAmt;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getNetprice() {
		return this.netprice;
	}

	public void setNetprice(String netprice) {
		this.netprice = netprice;
	}

	public String getTax4() {
		return this.tax4;
	}

	public void setTax4(String tax4) {
		this.tax4 = tax4;
	}

	public String getTax5() {
		return this.tax5;
	}

	public void setTax5(String tax5) {
		this.tax5 = tax5;
	}

	public String getTax6() {
		return this.tax6;
	}

	public void setTax6(String tax6) {
		this.tax6 = tax6;
	}

}
