package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCustomerportalFieldsId generated by hbm2java
 */
public class VtigerCustomerportalFieldsId implements java.io.Serializable {

	private int tabid;
	private Integer fieldid;
	private Integer visible;

	public VtigerCustomerportalFieldsId() {
	}

	public VtigerCustomerportalFieldsId(int tabid) {
		this.tabid = tabid;
	}

	public VtigerCustomerportalFieldsId(int tabid, Integer fieldid,
			Integer visible) {
		this.tabid = tabid;
		this.fieldid = fieldid;
		this.visible = visible;
	}

	public int getTabid() {
		return this.tabid;
	}

	public void setTabid(int tabid) {
		this.tabid = tabid;
	}

	public Integer getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(Integer fieldid) {
		this.fieldid = fieldid;
	}

	public Integer getVisible() {
		return this.visible;
	}

	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerCustomerportalFieldsId))
			return false;
		VtigerCustomerportalFieldsId castOther = (VtigerCustomerportalFieldsId) other;

		return (this.getTabid() == castOther.getTabid())
				&& ((this.getFieldid() == castOther.getFieldid()) || (this
						.getFieldid() != null && castOther.getFieldid() != null && this
						.getFieldid().equals(castOther.getFieldid())))
				&& ((this.getVisible() == castOther.getVisible()) || (this
						.getVisible() != null && castOther.getVisible() != null && this
						.getVisible().equals(castOther.getVisible())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getTabid();
		result = 37 * result
				+ (getFieldid() == null ? 0 : this.getFieldid().hashCode());
		result = 37 * result
				+ (getVisible() == null ? 0 : this.getVisible().hashCode());
		return result;
	}

}
