package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCashreceiptcf generated by hbm2java
 */
public class VtigerCashreceiptcf implements java.io.Serializable {

	private int cashreceiptid;

	public VtigerCashreceiptcf() {
	}

	public VtigerCashreceiptcf(int cashreceiptid) {
		this.cashreceiptid = cashreceiptid;
	}

	public int getCashreceiptid() {
		return this.cashreceiptid;
	}

	public void setCashreceiptid(int cashreceiptid) {
		this.cashreceiptid = cashreceiptid;
	}

}
