package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUser2role generated by hbm2java
 */
public class VtigerUser2role implements java.io.Serializable {

	private int userid;
	private String roleid;

	public VtigerUser2role() {
	}

	public VtigerUser2role(int userid, String roleid) {
		this.userid = userid;
		this.roleid = roleid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public String getRoleid() {
		return this.roleid;
	}

	public void setRoleid(String roleid) {
		this.roleid = roleid;
	}

}
