package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerProductcf generated by hbm2java
 */
public class VtigerProductcf implements java.io.Serializable {

	private int productid;
	private String cf833;
	private String cf834;
	private String cf835;

	public VtigerProductcf() {
	}

	public VtigerProductcf(int productid) {
		this.productid = productid;
	}

	public VtigerProductcf(int productid, String cf833, String cf834,
			String cf835) {
		this.productid = productid;
		this.cf833 = cf833;
		this.cf834 = cf834;
		this.cf835 = cf835;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public String getCf833() {
		return this.cf833;
	}

	public void setCf833(String cf833) {
		this.cf833 = cf833;
	}

	public String getCf834() {
		return this.cf834;
	}

	public void setCf834(String cf834) {
		this.cf834 = cf834;
	}

	public String getCf835() {
		return this.cf835;
	}

	public void setCf835(String cf835) {
		this.cf835 = cf835;
	}

}
