package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerWarehousecf generated by hbm2java
 */
public class VtigerWarehousecf implements java.io.Serializable {

	private int warehouseid;

	public VtigerWarehousecf() {
	}

	public VtigerWarehousecf(int warehouseid) {
		this.warehouseid = warehouseid;
	}

	public int getWarehouseid() {
		return this.warehouseid;
	}

	public void setWarehouseid(int warehouseid) {
		this.warehouseid = warehouseid;
	}

}
