package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContpotentialrelId generated by hbm2java
 */
public class VtigerContpotentialrelId implements java.io.Serializable {

	private int contactid;
	private int potentialid;

	public VtigerContpotentialrelId() {
	}

	public VtigerContpotentialrelId(int contactid, int potentialid) {
		this.contactid = contactid;
		this.potentialid = potentialid;
	}

	public int getContactid() {
		return this.contactid;
	}

	public void setContactid(int contactid) {
		this.contactid = contactid;
	}

	public int getPotentialid() {
		return this.potentialid;
	}

	public void setPotentialid(int potentialid) {
		this.potentialid = potentialid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerContpotentialrelId))
			return false;
		VtigerContpotentialrelId castOther = (VtigerContpotentialrelId) other;

		return (this.getContactid() == castOther.getContactid())
				&& (this.getPotentialid() == castOther.getPotentialid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getContactid();
		result = 37 * result + this.getPotentialid();
		return result;
	}

}
