package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCategoryId generated by hbm2java
 */
public class VtigerCategoryId implements java.io.Serializable {

	private int categoryid;
	private String categoryname;

	public VtigerCategoryId() {
	}

	public VtigerCategoryId(int categoryid, String categoryname) {
		this.categoryid = categoryid;
		this.categoryname = categoryname;
	}

	public int getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(int categoryid) {
		this.categoryid = categoryid;
	}

	public String getCategoryname() {
		return this.categoryname;
	}

	public void setCategoryname(String categoryname) {
		this.categoryname = categoryname;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerCategoryId))
			return false;
		VtigerCategoryId castOther = (VtigerCategoryId) other;

		return (this.getCategoryid() == castOther.getCategoryid())
				&& ((this.getCategoryname() == castOther.getCategoryname()) || (this
						.getCategoryname() != null
						&& castOther.getCategoryname() != null && this
						.getCategoryname().equals(castOther.getCategoryname())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCategoryid();
		result = 37
				* result
				+ (getCategoryname() == null ? 0 : this.getCategoryname()
						.hashCode());
		return result;
	}

}
