package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCrmentity generated by hbm2java
 */
public class VtigerCrmentity implements java.io.Serializable {

	private int crmid;
	private int version;
	private int smcreatorid;
	private int smownerid;
	private int modifiedby;
	private String setype;
	private String description;
	private String createdtime;
	private String modifiedtime;
	private String viewedtime;
	private String status;
	private Integer presence;
	private int deleted;
	private VtigerAccount vtigerAccount;

	public VtigerCrmentity() {
	}

	public VtigerCrmentity(int crmid, int smcreatorid, int smownerid,
			int modifiedby, String setype, String createdtime,
			String modifiedtime, int deleted) {
		this.crmid = crmid;
		this.smcreatorid = smcreatorid;
		this.smownerid = smownerid;
		this.modifiedby = modifiedby;
		this.setype = setype;
		this.createdtime = createdtime;
		this.modifiedtime = modifiedtime;
		this.deleted = deleted;
	}

	public VtigerCrmentity(int crmid, int smcreatorid, int smownerid,
			int modifiedby, String setype, String description,
			String createdtime, String modifiedtime, String viewedtime,
			String status, Integer presence, int deleted,
			VtigerAccount vtigerAccount) {
		this.crmid = crmid;
		this.smcreatorid = smcreatorid;
		this.smownerid = smownerid;
		this.modifiedby = modifiedby;
		this.setype = setype;
		this.description = description;
		this.createdtime = createdtime;
		this.modifiedtime = modifiedtime;
		this.viewedtime = viewedtime;
		this.status = status;
		this.presence = presence;
		this.deleted = deleted;
		this.vtigerAccount = vtigerAccount;
	}

	public VtigerCrmentity(int crmid, int smcreatorid, int smownerid,
			int modifiedby, String setype, String createdtime,
			String modifiedtime, String viewedtime, int version,
			Integer presence, int deleted) {
		this.crmid = crmid;
		this.smcreatorid = smcreatorid;
		this.smownerid = smownerid;
		this.modifiedby = modifiedby;
		this.setype = setype;
		this.createdtime = createdtime;
		this.modifiedtime = modifiedtime;
		this.viewedtime = viewedtime;
		this.version = version;
		this.presence = presence;
		this.deleted = deleted;

	}

	public int getCrmid() {
		return this.crmid;
	}

	public void setCrmid(int crmid) {
		this.crmid = crmid;
	}

	public int getVersion() {
		return this.version;
	}

	public void setVersion(int version) {
		this.version = version;
	}

	public int getSmcreatorid() {
		return this.smcreatorid;
	}

	public void setSmcreatorid(int smcreatorid) {
		this.smcreatorid = smcreatorid;
	}

	public int getSmownerid() {
		return this.smownerid;
	}

	public void setSmownerid(int smownerid) {
		this.smownerid = smownerid;
	}

	public int getModifiedby() {
		return this.modifiedby;
	}

	public void setModifiedby(int modifiedby) {
		this.modifiedby = modifiedby;
	}

	public String getSetype() {
		return this.setype;
	}

	public void setSetype(String setype) {
		this.setype = setype;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getCreatedtime() {
		return this.createdtime;
	}

	public void setCreatedtime(String createdtime) {
		this.createdtime = createdtime;
	}

	public String getModifiedtime() {
		return this.modifiedtime;
	}

	public void setModifiedtime(String modifiedtime) {
		this.modifiedtime = modifiedtime;
	}

	public String getViewedtime() {
		return this.viewedtime;
	}

	public void setViewedtime(String viewedtime) {
		this.viewedtime = viewedtime;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public Integer getPresence() {
		return this.presence;
	}

	public void setPresence(Integer presence) {
		this.presence = presence;
	}

	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public VtigerAccount getVtigerAccount() {
		return this.vtigerAccount;
	}

	public void setVtigerAccount(VtigerAccount vtigerAccount) {
		this.vtigerAccount = vtigerAccount;
	}

}
