package com.vendhaq.models;

// Generated Dec 13, 2012 3:37:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VtigerRoyality generated by hbm2java
 */
public class VtigerRoyality implements java.io.Serializable {

	private int royalityid;
	private int royalityCount;
	private String royalityamount;
	private Date fromDate;
	private Date toDate;
	private short deleted;

	public VtigerRoyality() {
	}

	public VtigerRoyality(int royalityid, int royalityCount, String royalityamount, short deleted) {
		this.royalityid = royalityid;
		this.royalityCount = royalityCount;
		this.royalityamount = royalityamount;
		this.deleted = deleted;
	}

	public VtigerRoyality(int royalityid, int royalityCount, String royalityamount, Date fromDate, Date toDate, short deleted) {
		this.royalityid = royalityid;
		this.royalityCount = royalityCount;
		this.royalityamount = royalityamount;
		this.fromDate = fromDate;
		this.toDate = toDate;
		this.deleted = deleted;
	}

	public int getRoyalityid() {
		return this.royalityid;
	}

	public void setRoyalityid(int royalityid) {
		this.royalityid = royalityid;
	}

	public int getRoyalityCount() {
		return this.royalityCount;
	}

	public void setRoyalityCount(int royalityCount) {
		this.royalityCount = royalityCount;
	}

	public String getRoyalityamount() {
		return this.royalityamount;
	}

	public void setRoyalityamount(String royalityamount) {
		this.royalityamount = royalityamount;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

	public short getDeleted() {
		return this.deleted;
	}

	public void setDeleted(short deleted) {
		this.deleted = deleted;
	}

}
