package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerProducttaxrel generated by hbm2java
 */
public class VtigerProducttaxrel implements java.io.Serializable {

	private VtigerProducttaxrelId id;

	public VtigerProducttaxrel() {
	}

	public VtigerProducttaxrel(VtigerProducttaxrelId id) {
		this.id = id;
	}

	public VtigerProducttaxrelId getId() {
		return this.id;
	}

	public void setId(VtigerProducttaxrelId id) {
		this.id = id;
	}

}
