package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInvoiceRecurringInfo generated by hbm2java
 */
public class VtigerInvoiceRecurringInfo implements java.io.Serializable {

	private VtigerInvoiceRecurringInfoId id;

	public VtigerInvoiceRecurringInfo() {
	}

	public VtigerInvoiceRecurringInfo(VtigerInvoiceRecurringInfoId id) {
		this.id = id;
	}

	public VtigerInvoiceRecurringInfoId getId() {
		return this.id;
	}

	public void setId(VtigerInvoiceRecurringInfoId id) {
		this.id = id;
	}

}
