package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerDateFormat generated by hbm2java
 */
public class VtigerDateFormat implements java.io.Serializable {

	private int dateFormatid;
	private String dateFormat;
	private int sortorderid;
	private int presence;

	public VtigerDateFormat() {
	}

	public VtigerDateFormat(int dateFormatid, String dateFormat,
			int sortorderid, int presence) {
		this.dateFormatid = dateFormatid;
		this.dateFormat = dateFormat;
		this.sortorderid = sortorderid;
		this.presence = presence;
	}

	public int getDateFormatid() {
		return this.dateFormatid;
	}

	public void setDateFormatid(int dateFormatid) {
		this.dateFormatid = dateFormatid;
	}

	public String getDateFormat() {
		return this.dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

	public int getSortorderid() {
		return this.sortorderid;
	}

	public void setSortorderid(int sortorderid) {
		this.sortorderid = sortorderid;
	}

	public int getPresence() {
		return this.presence;
	}

	public void setPresence(int presence) {
		this.presence = presence;
	}

}
