package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerBarcodeId generated by hbm2java
 */
public class VtigerBarcodeId implements java.io.Serializable {

	private int barcodeid;
	private String barcode;

	public VtigerBarcodeId() {
	}

	public VtigerBarcodeId(int barcodeid, String barcode) {
		this.barcodeid = barcodeid;
		this.barcode = barcode;
	}

	public int getBarcodeid() {
		return this.barcodeid;
	}

	public void setBarcodeid(int barcodeid) {
		this.barcodeid = barcodeid;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerBarcodeId))
			return false;
		VtigerBarcodeId castOther = (VtigerBarcodeId) other;

		return (this.getBarcodeid() == castOther.getBarcodeid())
				&& ((this.getBarcode() == castOther.getBarcode()) || (this
						.getBarcode() != null && castOther.getBarcode() != null && this
						.getBarcode().equals(castOther.getBarcode())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getBarcodeid();
		result = 37 * result
				+ (getBarcode() == null ? 0 : this.getBarcode().hashCode());
		return result;
	}

}
