package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerDateFormatSeq generated by hbm2java
 */
public class VtigerDateFormatSeq implements java.io.Serializable {

	private int id;

	public VtigerDateFormatSeq() {
	}

	public VtigerDateFormatSeq(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
