package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerBarcodecf generated by hbm2java
 */
public class VtigerBarcodecf implements java.io.Serializable {

	private int barcodeid;
	private String cf829;
	private String cf830;
	private String cf831;
	private String cf832;

	public VtigerBarcodecf() {
	}

	public VtigerBarcodecf(int barcodeid) {
		this.barcodeid = barcodeid;
	}

	public VtigerBarcodecf(int barcodeid, String cf829, String cf830,
			String cf831, String cf832) {
		this.barcodeid = barcodeid;
		this.cf829 = cf829;
		this.cf830 = cf830;
		this.cf831 = cf831;
		this.cf832 = cf832;
	}

	public int getBarcodeid() {
		return this.barcodeid;
	}

	public void setBarcodeid(int barcodeid) {
		this.barcodeid = barcodeid;
	}

	public String getCf829() {
		return this.cf829;
	}

	public void setCf829(String cf829) {
		this.cf829 = cf829;
	}

	public String getCf830() {
		return this.cf830;
	}

	public void setCf830(String cf830) {
		this.cf830 = cf830;
	}

	public String getCf831() {
		return this.cf831;
	}

	public void setCf831(String cf831) {
		this.cf831 = cf831;
	}

	public String getCf832() {
		return this.cf832;
	}

	public void setCf832(String cf832) {
		this.cf832 = cf832;
	}

}
