package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInventorysubproductrel generated by hbm2java
 */
public class VtigerInventorysubproductrel implements java.io.Serializable {

	private VtigerInventorysubproductrelId id;

	public VtigerInventorysubproductrel() {
	}

	public VtigerInventorysubproductrel(VtigerInventorysubproductrelId id) {
		this.id = id;
	}

	public VtigerInventorysubproductrelId getId() {
		return this.id;
	}

	public void setId(VtigerInventorysubproductrelId id) {
		this.id = id;
	}

}
