package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUsersSeq generated by hbm2java
 */
public class VtigerUsersSeq implements java.io.Serializable {

	private int id;

	public VtigerUsersSeq() {
	}

	public VtigerUsersSeq(int id) {
		this.id = id;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
