package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContacttype generated by hbm2java
 */
public class VtigerContacttype implements java.io.Serializable {

	private int contacttypeid;
	private String contacttype;
	private int sortorderid;
	private int presence;

	public VtigerContacttype() {
	}

	public VtigerContacttype(int contacttypeid, String contacttype,
			int sortorderid, int presence) {
		this.contacttypeid = contacttypeid;
		this.contacttype = contacttype;
		this.sortorderid = sortorderid;
		this.presence = presence;
	}

	public int getContacttypeid() {
		return this.contacttypeid;
	}

	public void setContacttypeid(int contacttypeid) {
		this.contacttypeid = contacttypeid;
	}

	public String getContacttype() {
		return this.contacttype;
	}

	public void setContacttype(String contacttype) {
		this.contacttype = contacttype;
	}

	public int getSortorderid() {
		return this.sortorderid;
	}

	public void setSortorderid(int sortorderid) {
		this.sortorderid = sortorderid;
	}

	public int getPresence() {
		return this.presence;
	}

	public void setPresence(int presence) {
		this.presence = presence;
	}

}
