package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCashreceiptId generated by hbm2java
 */
public class VtigerCashreceiptId implements java.io.Serializable {

	private int cashreceiptid;
	private int invoiceid;
	private int customerid;
	private String grandtotal;
	private String creditamount;
	private String paidamount;
	private String pendingamount;
	private String crediteddate;
	private String lastpaiddate;

	public VtigerCashreceiptId() {
	}

	public VtigerCashreceiptId(int cashreceiptid, int invoiceid, int customerid) {
		this.cashreceiptid = cashreceiptid;
		this.invoiceid = invoiceid;
		this.customerid = customerid;
	}

	public VtigerCashreceiptId(int cashreceiptid, int invoiceid,
			int customerid, String grandtotal, String creditamount,
			String paidamount, String pendingamount, String crediteddate,
			String lastpaiddate) {
		this.cashreceiptid = cashreceiptid;
		this.invoiceid = invoiceid;
		this.customerid = customerid;
		this.grandtotal = grandtotal;
		this.creditamount = creditamount;
		this.paidamount = paidamount;
		this.pendingamount = pendingamount;
		this.crediteddate = crediteddate;
		this.lastpaiddate = lastpaiddate;
	}

	

	public int getCashreceiptid() {
		return this.cashreceiptid;
	}

	public void setCashreceiptid(int cashreceiptid) {
		this.cashreceiptid = cashreceiptid;
	}

	public int getInvoiceid() {
		return this.invoiceid;
	}

	public void setInvoiceid(int invoiceid) {
		this.invoiceid = invoiceid;
	}

	public int getCustomerid() {
		return this.customerid;
	}

	public void setCustomerid(int customerid) {
		this.customerid = customerid;
	}

	public String getGrandtotal() {
		return this.grandtotal;
	}

	public void setGrandtotal(String grandtotal) {
		this.grandtotal = grandtotal;
	}

	public String getCreditamount() {
		return this.creditamount;
	}

	public void setCreditamount(String creditamount) {
		this.creditamount = creditamount;
	}

	public String getPaidamount() {
		return this.paidamount;
	}

	public void setPaidamount(String paidamount) {
		this.paidamount = paidamount;
	}

	public String getPendingamount() {
		return this.pendingamount;
	}

	public void setPendingamount(String pendingamount) {
		this.pendingamount = pendingamount;
	}

	public String getCrediteddate() {
		return this.crediteddate;
	}

	public void setCrediteddate(String crediteddate) {
		this.crediteddate = crediteddate;
	}

	public String getLastpaiddate() {
		return this.lastpaiddate;
	}

	public void setLastpaiddate(String lastpaiddate) {
		this.lastpaiddate = lastpaiddate;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerCashreceiptId))
			return false;
		VtigerCashreceiptId castOther = (VtigerCashreceiptId) other;

		return (this.getCashreceiptid() == castOther.getCashreceiptid())
				&& (this.getInvoiceid() == castOther.getInvoiceid())
				&& (this.getCustomerid() == castOther.getCustomerid())
				&& ((this.getGrandtotal() == castOther.getGrandtotal()) || (this
						.getGrandtotal() != null
						&& castOther.getGrandtotal() != null && this
						.getGrandtotal().equals(castOther.getGrandtotal())))
				&& ((this.getCreditamount() == castOther.getCreditamount()) || (this
						.getCreditamount() != null
						&& castOther.getCreditamount() != null && this
						.getCreditamount().equals(castOther.getCreditamount())))
				&& ((this.getPaidamount() == castOther.getPaidamount()) || (this
						.getPaidamount() != null
						&& castOther.getPaidamount() != null && this
						.getPaidamount().equals(castOther.getPaidamount())))
				&& ((this.getPendingamount() == castOther.getPendingamount()) || (this
						.getPendingamount() != null
						&& castOther.getPendingamount() != null && this
						.getPendingamount()
						.equals(castOther.getPendingamount())))
				&& ((this.getCrediteddate() == castOther.getCrediteddate()) || (this
						.getCrediteddate() != null
						&& castOther.getCrediteddate() != null && this
						.getCrediteddate().equals(castOther.getCrediteddate())))
				&& ((this.getLastpaiddate() == castOther.getLastpaiddate()) || (this
						.getLastpaiddate() != null
						&& castOther.getLastpaiddate() != null && this
						.getLastpaiddate().equals(castOther.getLastpaiddate())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCashreceiptid();
		result = 37 * result + this.getInvoiceid();
		result = 37 * result + this.getCustomerid();
		result = 37
				* result
				+ (getGrandtotal() == null ? 0 : this.getGrandtotal()
						.hashCode());
		result = 37
				* result
				+ (getCreditamount() == null ? 0 : this.getCreditamount()
						.hashCode());
		result = 37
				* result
				+ (getPaidamount() == null ? 0 : this.getPaidamount()
						.hashCode());
		result = 37
				* result
				+ (getPendingamount() == null ? 0 : this.getPendingamount()
						.hashCode());
		result = 37
				* result
				+ (getCrediteddate() == null ? 0 : this.getCrediteddate()
						.hashCode());
		result = 37
				* result
				+ (getLastpaiddate() == null ? 0 : this.getLastpaiddate()
						.hashCode());
		return result;
	}

}
