package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerProductcurrencyrel generated by hbm2java
 */
public class VtigerProductcurrencyrel implements java.io.Serializable {

	private VtigerProductcurrencyrelId id;

	public VtigerProductcurrencyrel() {
	}

	public VtigerProductcurrencyrel(VtigerProductcurrencyrelId id) {
		this.id = id;
	}

	public VtigerProductcurrencyrelId getId() {
		return this.id;
	}

	public void setId(VtigerProductcurrencyrelId id) {
		this.id = id;
	}

}
