package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerBarcode generated by hbm2java
 */
public class VtigerBarcode implements java.io.Serializable {

	private VtigerBarcodeId id;
	private String companyname;
	private String productName;
	private String price;
	private String vat;
	private String service;
	private String netprice;
	private String filename;
	private int category;
	private String size;
	private String barcodeColor;
	private String barcodeCost;
	private String markUp;
	private String barcodeWithcform;
	private String barcodeWithoutcform;

	public VtigerBarcode() {
	}

	public VtigerBarcode(VtigerBarcodeId id, String filename, int category) {
		this.id = id;
		this.filename = filename;
		this.category = category;
	}

	public VtigerBarcode(VtigerBarcodeId id, String companyname,
			String productName, String price, String vat, String service,
			String netprice, String filename, int category, String size,
			String barcodeColor, String barcodeCost, String markUp,
			String barcodeWithcform, String barcodeWithoutcform) {
		this.id = id;
		this.companyname = companyname;
		this.productName = productName;
		this.price = price;
		this.vat = vat;
		this.service = service;
		this.netprice = netprice;
		this.filename = filename;
		this.category = category;
		this.size = size;
		this.barcodeColor = barcodeColor;
		this.barcodeCost = barcodeCost;
		this.markUp = markUp;
		this.barcodeWithcform = barcodeWithcform;
		this.barcodeWithoutcform = barcodeWithoutcform;
	}

	public VtigerBarcodeId getId() {
		return this.id;
	}

	public void setId(VtigerBarcodeId id) {
		this.id = id;
	}

	public String getCompanyname() {
		return this.companyname;
	}

	public void setCompanyname(String companyname) {
		this.companyname = companyname;
	}

	public String getProductName() {
		return this.productName;
	}

	public void setProductName(String productName) {
		this.productName = productName;
	}

	public String getPrice() {
		return this.price;
	}

	public void setPrice(String price) {
		this.price = price;
	}

	public String getVat() {
		return this.vat;
	}

	public void setVat(String vat) {
		this.vat = vat;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getNetprice() {
		return this.netprice;
	}

	public void setNetprice(String netprice) {
		this.netprice = netprice;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public int getCategory() {
		return this.category;
	}

	public void setCategory(int category) {
		this.category = category;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String getBarcodeColor() {
		return this.barcodeColor;
	}

	public void setBarcodeColor(String barcodeColor) {
		this.barcodeColor = barcodeColor;
	}

	public String getBarcodeCost() {
		return this.barcodeCost;
	}

	public void setBarcodeCost(String barcodeCost) {
		this.barcodeCost = barcodeCost;
	}

	public String getMarkUp() {
		return this.markUp;
	}

	public void setMarkUp(String markUp) {
		this.markUp = markUp;
	}

	public String getBarcodeWithcform() {
		return this.barcodeWithcform;
	}

	public void setBarcodeWithcform(String barcodeWithcform) {
		this.barcodeWithcform = barcodeWithcform;
	}

	public String getBarcodeWithoutcform() {
		return this.barcodeWithoutcform;
	}

	public void setBarcodeWithoutcform(String barcodeWithoutcform) {
		this.barcodeWithoutcform = barcodeWithoutcform;
	}

}
