package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerAccount generated by hbm2java
 */
public class VtigerAccount implements java.io.Serializable {

	private int accountid;
	private VtigerCrmentity vtigerCrmentity;
	private String accountNo;
	private String accountname;
	private Integer parentid;
	private String accountType;
	private String industry;
	private Integer annualrevenue;
	private String rating;
	private String ownership;
	private String siccode;
	private String tickersymbol;
	private String phone;
	private String otherphone;
	private String email1;
	private String email2;
	private String website;
	private String fax;
	private Integer employees;
	private String emailoptout;
	private String notifyOwner;

	public VtigerAccount() {
	}

	public VtigerAccount(VtigerCrmentity vtigerCrmentity, String accountNo,
			String accountname) {
		this.vtigerCrmentity = vtigerCrmentity;
		this.accountNo = accountNo;
		this.accountname = accountname;
	}

	public VtigerAccount(VtigerCrmentity vtigerCrmentity, String accountNo,
			String accountname, Integer parentid, String accountType,
			String industry, Integer annualrevenue, String rating,
			String ownership, String siccode, String tickersymbol,
			String phone, String otherphone, String email1, String email2,
			String website, String fax, Integer employees, String emailoptout,
			String notifyOwner) {
		this.vtigerCrmentity = vtigerCrmentity;
		this.accountNo = accountNo;
		this.accountname = accountname;
		this.parentid = parentid;
		this.accountType = accountType;
		this.industry = industry;
		this.annualrevenue = annualrevenue;
		this.rating = rating;
		this.ownership = ownership;
		this.siccode = siccode;
		this.tickersymbol = tickersymbol;
		this.phone = phone;
		this.otherphone = otherphone;
		this.email1 = email1;
		this.email2 = email2;
		this.website = website;
		this.fax = fax;
		this.employees = employees;
		this.emailoptout = emailoptout;
		this.notifyOwner = notifyOwner;
	}

	public int getAccountid() {
		return this.accountid;
	}

	public void setAccountid(int accountid) {
		this.accountid = accountid;
	}

	public VtigerCrmentity getVtigerCrmentity() {
		return this.vtigerCrmentity;
	}

	public void setVtigerCrmentity(VtigerCrmentity vtigerCrmentity) {
		this.vtigerCrmentity = vtigerCrmentity;
	}

	public String getAccountNo() {
		return this.accountNo;
	}

	public void setAccountNo(String accountNo) {
		this.accountNo = accountNo;
	}

	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	public Integer getParentid() {
		return this.parentid;
	}

	public void setParentid(Integer parentid) {
		this.parentid = parentid;
	}

	public String getAccountType() {
		return this.accountType;
	}

	public void setAccountType(String accountType) {
		this.accountType = accountType;
	}

	public String getIndustry() {
		return this.industry;
	}

	public void setIndustry(String industry) {
		this.industry = industry;
	}

	public Integer getAnnualrevenue() {
		return this.annualrevenue;
	}

	public void setAnnualrevenue(Integer annualrevenue) {
		this.annualrevenue = annualrevenue;
	}

	public String getRating() {
		return this.rating;
	}

	public void setRating(String rating) {
		this.rating = rating;
	}

	public String getOwnership() {
		return this.ownership;
	}

	public void setOwnership(String ownership) {
		this.ownership = ownership;
	}

	public String getSiccode() {
		return this.siccode;
	}

	public void setSiccode(String siccode) {
		this.siccode = siccode;
	}

	public String getTickersymbol() {
		return this.tickersymbol;
	}

	public void setTickersymbol(String tickersymbol) {
		this.tickersymbol = tickersymbol;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getOtherphone() {
		return this.otherphone;
	}

	public void setOtherphone(String otherphone) {
		this.otherphone = otherphone;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public Integer getEmployees() {
		return this.employees;
	}

	public void setEmployees(Integer employees) {
		this.employees = employees;
	}

	public String getEmailoptout() {
		return this.emailoptout;
	}

	public void setEmailoptout(String emailoptout) {
		this.emailoptout = emailoptout;
	}

	public String getNotifyOwner() {
		return this.notifyOwner;
	}

	public void setNotifyOwner(String notifyOwner) {
		this.notifyOwner = notifyOwner;
	}

}
