package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContactscf generated by hbm2java
 */
public class VtigerContactscf implements java.io.Serializable {

	private int contactid;

	public VtigerContactscf() {
	}

	public VtigerContactscf(int contactid) {
		this.contactid = contactid;
	}

	public int getContactid() {
		return this.contactid;
	}

	public void setContactid(int contactid) {
		this.contactid = contactid;
	}

}
