package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInventoryshippingrelId generated by hbm2java
 */
public class VtigerInventoryshippingrelId implements java.io.Serializable {

	private Integer id;
	private String shtax1;
	private String shtax2;
	private String shtax3;

	public VtigerInventoryshippingrelId() {
	}

	public VtigerInventoryshippingrelId(Integer id, String shtax1,
			String shtax2, String shtax3) {
		this.id = id;
		this.shtax1 = shtax1;
		this.shtax2 = shtax2;
		this.shtax3 = shtax3;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public String getShtax1() {
		return this.shtax1;
	}

	public void setShtax1(String shtax1) {
		this.shtax1 = shtax1;
	}

	public String getShtax2() {
		return this.shtax2;
	}

	public void setShtax2(String shtax2) {
		this.shtax2 = shtax2;
	}

	public String getShtax3() {
		return this.shtax3;
	}

	public void setShtax3(String shtax3) {
		this.shtax3 = shtax3;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerInventoryshippingrelId))
			return false;
		VtigerInventoryshippingrelId castOther = (VtigerInventoryshippingrelId) other;

		return ((this.getId() == castOther.getId()) || (this.getId() != null
				&& castOther.getId() != null && this.getId().equals(
				castOther.getId())))
				&& ((this.getShtax1() == castOther.getShtax1()) || (this
						.getShtax1() != null && castOther.getShtax1() != null && this
						.getShtax1().equals(castOther.getShtax1())))
				&& ((this.getShtax2() == castOther.getShtax2()) || (this
						.getShtax2() != null && castOther.getShtax2() != null && this
						.getShtax2().equals(castOther.getShtax2())))
				&& ((this.getShtax3() == castOther.getShtax3()) || (this
						.getShtax3() != null && castOther.getShtax3() != null && this
						.getShtax3().equals(castOther.getShtax3())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getId() == null ? 0 : this.getId().hashCode());
		result = 37 * result
				+ (getShtax1() == null ? 0 : this.getShtax1().hashCode());
		result = 37 * result
				+ (getShtax2() == null ? 0 : this.getShtax2().hashCode());
		result = 37 * result
				+ (getShtax3() == null ? 0 : this.getShtax3().hashCode());
		return result;
	}

}
