package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUsers2group generated by hbm2java
 */
public class VtigerUsers2group implements java.io.Serializable {

	private VtigerUsers2groupId id;

	public VtigerUsers2group() {
	}

	public VtigerUsers2group(VtigerUsers2groupId id) {
		this.id = id;
	}

	public VtigerUsers2groupId getId() {
		return this.id;
	}

	public void setId(VtigerUsers2groupId id) {
		this.id = id;
	}

}
