package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUser2mergefieldsId generated by hbm2java
 */
public class VtigerUser2mergefieldsId implements java.io.Serializable {

	private Integer userid;
	private Integer tabid;
	private Integer fieldid;
	private Integer visible;

	public VtigerUser2mergefieldsId() {
	}

	public VtigerUser2mergefieldsId(Integer userid, Integer tabid,
			Integer fieldid, Integer visible) {
		this.userid = userid;
		this.tabid = tabid;
		this.fieldid = fieldid;
		this.visible = visible;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public Integer getTabid() {
		return this.tabid;
	}

	public void setTabid(Integer tabid) {
		this.tabid = tabid;
	}

	public Integer getFieldid() {
		return this.fieldid;
	}

	public void setFieldid(Integer fieldid) {
		this.fieldid = fieldid;
	}

	public Integer getVisible() {
		return this.visible;
	}

	public void setVisible(Integer visible) {
		this.visible = visible;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerUser2mergefieldsId))
			return false;
		VtigerUser2mergefieldsId castOther = (VtigerUser2mergefieldsId) other;

		return ((this.getUserid() == castOther.getUserid()) || (this
				.getUserid() != null && castOther.getUserid() != null && this
				.getUserid().equals(castOther.getUserid())))
				&& ((this.getTabid() == castOther.getTabid()) || (this
						.getTabid() != null && castOther.getTabid() != null && this
						.getTabid().equals(castOther.getTabid())))
				&& ((this.getFieldid() == castOther.getFieldid()) || (this
						.getFieldid() != null && castOther.getFieldid() != null && this
						.getFieldid().equals(castOther.getFieldid())))
				&& ((this.getVisible() == castOther.getVisible()) || (this
						.getVisible() != null && castOther.getVisible() != null && this
						.getVisible().equals(castOther.getVisible())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result
				+ (getUserid() == null ? 0 : this.getUserid().hashCode());
		result = 37 * result
				+ (getTabid() == null ? 0 : this.getTabid().hashCode());
		result = 37 * result
				+ (getFieldid() == null ? 0 : this.getFieldid().hashCode());
		result = 37 * result
				+ (getVisible() == null ? 0 : this.getVisible().hashCode());
		return result;
	}

}
