package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContactaddress generated by hbm2java
 */
public class VtigerContactaddress implements java.io.Serializable {

	private int contactaddressid;
	private String mailingcity;
	private String mailingstreet;
	private String mailingcountry;
	private String othercountry;
	private String mailingstate;
	private String mailingpobox;
	private String othercity;
	private String otherstate;
	private String mailingzip;
	private String otherzip;
	private String otherstreet;
	private String otherpobox;

	public VtigerContactaddress() {
	}

	public VtigerContactaddress(int contactaddressid) {
		this.contactaddressid = contactaddressid;
	}

	public VtigerContactaddress(int contactaddressid, String mailingcity,
			String mailingstreet, String mailingcountry, String othercountry,
			String mailingstate, String mailingpobox, String othercity,
			String otherstate, String mailingzip, String otherzip,
			String otherstreet, String otherpobox) {
		this.contactaddressid = contactaddressid;
		this.mailingcity = mailingcity;
		this.mailingstreet = mailingstreet;
		this.mailingcountry = mailingcountry;
		this.othercountry = othercountry;
		this.mailingstate = mailingstate;
		this.mailingpobox = mailingpobox;
		this.othercity = othercity;
		this.otherstate = otherstate;
		this.mailingzip = mailingzip;
		this.otherzip = otherzip;
		this.otherstreet = otherstreet;
		this.otherpobox = otherpobox;
	}

	public int getContactaddressid() {
		return this.contactaddressid;
	}

	public void setContactaddressid(int contactaddressid) {
		this.contactaddressid = contactaddressid;
	}

	public String getMailingcity() {
		return this.mailingcity;
	}

	public void setMailingcity(String mailingcity) {
		this.mailingcity = mailingcity;
	}

	public String getMailingstreet() {
		return this.mailingstreet;
	}

	public void setMailingstreet(String mailingstreet) {
		this.mailingstreet = mailingstreet;
	}

	public String getMailingcountry() {
		return this.mailingcountry;
	}

	public void setMailingcountry(String mailingcountry) {
		this.mailingcountry = mailingcountry;
	}

	public String getOthercountry() {
		return this.othercountry;
	}

	public void setOthercountry(String othercountry) {
		this.othercountry = othercountry;
	}

	public String getMailingstate() {
		return this.mailingstate;
	}

	public void setMailingstate(String mailingstate) {
		this.mailingstate = mailingstate;
	}

	public String getMailingpobox() {
		return this.mailingpobox;
	}

	public void setMailingpobox(String mailingpobox) {
		this.mailingpobox = mailingpobox;
	}

	public String getOthercity() {
		return this.othercity;
	}

	public void setOthercity(String othercity) {
		this.othercity = othercity;
	}

	public String getOtherstate() {
		return this.otherstate;
	}

	public void setOtherstate(String otherstate) {
		this.otherstate = otherstate;
	}

	public String getMailingzip() {
		return this.mailingzip;
	}

	public void setMailingzip(String mailingzip) {
		this.mailingzip = mailingzip;
	}

	public String getOtherzip() {
		return this.otherzip;
	}

	public void setOtherzip(String otherzip) {
		this.otherzip = otherzip;
	}

	public String getOtherstreet() {
		return this.otherstreet;
	}

	public void setOtherstreet(String otherstreet) {
		this.otherstreet = otherstreet;
	}

	public String getOtherpobox() {
		return this.otherpobox;
	}

	public void setOtherpobox(String otherpobox) {
		this.otherpobox = otherpobox;
	}

}
