package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerProducts generated by hbm2java
 */
public class VtigerProducts implements java.io.Serializable {

	private int productid;
	private String productNo;
	private String productname;
	private String barcode;
	private String warehouseId;
	private String productcode;
	private String productcategory;
	private String manufacturer;
	private String qtyPerUnit;
	private String cost;
	private String unitPrice;
	private String discount;
	private String netprice;
	private String vat;
	private String service;
	private String frequency;
	private String weight;
	private Integer packSize;
	private String salesStartDate;
	private String salesEndDate;
	private String startDate;
	private String expiryDate;
	private Integer costFactor;
	private String commissionrate;
	private String commissionmethod;
	private int discontinued;
	private String usageunit;
	private Integer handler;
	private Integer reorderlevel;
	private String website;
	private String taxclass;
	private String mfrPartNo;
	private String vendorPartNo;
	private String serialno;
	private String qtyinstock;
	private String productsheet;
	private Integer qtyindemand;
	private String glacct;
	private Integer vendorId;
	private String imagename;
	private int currencyId;
	private String productMarkup;
	private String productWithcform;
	private String productWithoutcform;

	public VtigerProducts() {
	}

	public VtigerProducts(int productid, String productNo, String productname,
			int discontinued, int currencyId) {
		this.productid = productid;
		this.productNo = productNo;
		this.productname = productname;
		this.discontinued = discontinued;
		this.currencyId = currencyId;
	}

	public VtigerProducts(int productid, String productNo, String productname,
			String barcode, String warehouseId, String productcode,
			String productcategory, String manufacturer, String qtyPerUnit,
			String cost, String unitPrice, String discount, String netprice,
			String vat, String service, String frequency, String weight,
			Integer packSize, String salesStartDate, String salesEndDate,
			String startDate, String expiryDate, Integer costFactor,
			String commissionrate, String commissionmethod, int discontinued,
			String usageunit, Integer handler, Integer reorderlevel,
			String website, String taxclass, String mfrPartNo,
			String vendorPartNo, String serialno, String qtyinstock,
			String productsheet, Integer qtyindemand, String glacct,
			Integer vendorId, String imagename, int currencyId,
			String productMarkup, String productWithcform,
			String productWithoutcform) {
		this.productid = productid;
		this.productNo = productNo;
		this.productname = productname;
		this.barcode = barcode;
		this.warehouseId = warehouseId;
		this.productcode = productcode;
		this.productcategory = productcategory;
		this.manufacturer = manufacturer;
		this.qtyPerUnit = qtyPerUnit;
		this.cost = cost;
		this.unitPrice = unitPrice;
		this.discount = discount;
		this.netprice = netprice;
		this.vat = vat;
		this.service = service;
		this.frequency = frequency;
		this.weight = weight;
		this.packSize = packSize;
		this.salesStartDate = salesStartDate;
		this.salesEndDate = salesEndDate;
		this.startDate = startDate;
		this.expiryDate = expiryDate;
		this.costFactor = costFactor;
		this.commissionrate = commissionrate;
		this.commissionmethod = commissionmethod;
		this.discontinued = discontinued;
		this.usageunit = usageunit;
		this.handler = handler;
		this.reorderlevel = reorderlevel;
		this.website = website;
		this.taxclass = taxclass;
		this.mfrPartNo = mfrPartNo;
		this.vendorPartNo = vendorPartNo;
		this.serialno = serialno;
		this.qtyinstock = qtyinstock;
		this.productsheet = productsheet;
		this.qtyindemand = qtyindemand;
		this.glacct = glacct;
		this.vendorId = vendorId;
		this.imagename = imagename;
		this.currencyId = currencyId;
		this.productMarkup = productMarkup;
		this.productWithcform = productWithcform;
		this.productWithoutcform = productWithoutcform;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public String getProductNo() {
		return this.productNo;
	}

	public void setProductNo(String productNo) {
		this.productNo = productNo;
	}

	public String getProductname() {
		return this.productname;
	}

	public void setProductname(String productname) {
		this.productname = productname;
	}

	public String getBarcode() {
		return this.barcode;
	}

	public void setBarcode(String barcode) {
		this.barcode = barcode;
	}

	public String getWarehouseId() {
		return this.warehouseId;
	}

	public void setWarehouseId(String warehouseId) {
		this.warehouseId = warehouseId;
	}

	public String getProductcode() {
		return this.productcode;
	}

	public void setProductcode(String productcode) {
		this.productcode = productcode;
	}

	public String getProductcategory() {
		return this.productcategory;
	}

	public void setProductcategory(String productcategory) {
		this.productcategory = productcategory;
	}

	public String getManufacturer() {
		return this.manufacturer;
	}

	public void setManufacturer(String manufacturer) {
		this.manufacturer = manufacturer;
	}

	public String getQtyPerUnit() {
		return this.qtyPerUnit;
	}

	public void setQtyPerUnit(String qtyPerUnit) {
		this.qtyPerUnit = qtyPerUnit;
	}

	public String getCost() {
		return this.cost;
	}

	public void setCost(String cost) {
		this.cost = cost;
	}

	public String getUnitPrice() {
		return this.unitPrice;
	}

	public void setUnitPrice(String unitPrice) {
		this.unitPrice = unitPrice;
	}

	public String getDiscount() {
		return this.discount;
	}

	public void setDiscount(String discount) {
		this.discount = discount;
	}

	public String getNetprice() {
		return this.netprice;
	}

	public void setNetprice(String netprice) {
		this.netprice = netprice;
	}

	public String getVat() {
		return this.vat;
	}

	public void setVat(String vat) {
		this.vat = vat;
	}

	public String getService() {
		return this.service;
	}

	public void setService(String service) {
		this.service = service;
	}

	public String getFrequency() {
		return this.frequency;
	}

	public void setFrequency(String frequency) {
		this.frequency = frequency;
	}

	public String getWeight() {
		return this.weight;
	}

	public void setWeight(String weight) {
		this.weight = weight;
	}

	public Integer getPackSize() {
		return this.packSize;
	}

	public void setPackSize(Integer packSize) {
		this.packSize = packSize;
	}

	public String getSalesStartDate() {
		return this.salesStartDate;
	}

	public void setSalesStartDate(String salesStartDate) {
		this.salesStartDate = salesStartDate;
	}

	public String getSalesEndDate() {
		return this.salesEndDate;
	}

	public void setSalesEndDate(String salesEndDate) {
		this.salesEndDate = salesEndDate;
	}

	public String getStartDate() {
		return this.startDate;
	}

	public void setStartDate(String startDate) {
		this.startDate = startDate;
	}

	public String getExpiryDate() {
		return this.expiryDate;
	}

	public void setExpiryDate(String expiryDate) {
		this.expiryDate = expiryDate;
	}

	public Integer getCostFactor() {
		return this.costFactor;
	}

	public void setCostFactor(Integer costFactor) {
		this.costFactor = costFactor;
	}

	public String getCommissionrate() {
		return this.commissionrate;
	}

	public void setCommissionrate(String commissionrate) {
		this.commissionrate = commissionrate;
	}

	public String getCommissionmethod() {
		return this.commissionmethod;
	}

	public void setCommissionmethod(String commissionmethod) {
		this.commissionmethod = commissionmethod;
	}

	public int getDiscontinued() {
		return this.discontinued;
	}

	public void setDiscontinued(int discontinued) {
		this.discontinued = discontinued;
	}

	public String getUsageunit() {
		return this.usageunit;
	}

	public void setUsageunit(String usageunit) {
		this.usageunit = usageunit;
	}

	public Integer getHandler() {
		return this.handler;
	}

	public void setHandler(Integer handler) {
		this.handler = handler;
	}

	public Integer getReorderlevel() {
		return this.reorderlevel;
	}

	public void setReorderlevel(Integer reorderlevel) {
		this.reorderlevel = reorderlevel;
	}

	public String getWebsite() {
		return this.website;
	}

	public void setWebsite(String website) {
		this.website = website;
	}

	public String getTaxclass() {
		return this.taxclass;
	}

	public void setTaxclass(String taxclass) {
		this.taxclass = taxclass;
	}

	public String getMfrPartNo() {
		return this.mfrPartNo;
	}

	public void setMfrPartNo(String mfrPartNo) {
		this.mfrPartNo = mfrPartNo;
	}

	public String getVendorPartNo() {
		return this.vendorPartNo;
	}

	public void setVendorPartNo(String vendorPartNo) {
		this.vendorPartNo = vendorPartNo;
	}

	public String getSerialno() {
		return this.serialno;
	}

	public void setSerialno(String serialno) {
		this.serialno = serialno;
	}

	public String getQtyinstock() {
		return this.qtyinstock;
	}

	public void setQtyinstock(String qtyinstock) {
		this.qtyinstock = qtyinstock;
	}

	public String getProductsheet() {
		return this.productsheet;
	}

	public void setProductsheet(String productsheet) {
		this.productsheet = productsheet;
	}

	public Integer getQtyindemand() {
		return this.qtyindemand;
	}

	public void setQtyindemand(Integer qtyindemand) {
		this.qtyindemand = qtyindemand;
	}

	public String getGlacct() {
		return this.glacct;
	}

	public void setGlacct(String glacct) {
		this.glacct = glacct;
	}

	public Integer getVendorId() {
		return this.vendorId;
	}

	public void setVendorId(Integer vendorId) {
		this.vendorId = vendorId;
	}

	public String getImagename() {
		return this.imagename;
	}

	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	public int getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(int currencyId) {
		this.currencyId = currencyId;
	}

	public String getProductMarkup() {
		return this.productMarkup;
	}

	public void setProductMarkup(String productMarkup) {
		this.productMarkup = productMarkup;
	}

	public String getProductWithcform() {
		return this.productWithcform;
	}

	public void setProductWithcform(String productWithcform) {
		this.productWithcform = productWithcform;
	}

	public String getProductWithoutcform() {
		return this.productWithoutcform;
	}

	public void setProductWithoutcform(String productWithoutcform) {
		this.productWithoutcform = productWithoutcform;
	}

	@Override
	public String toString() {
		super.toString();
		String string = "Product id:" + productid + " barcode:" + barcode
				+ " product name:" + productname + " unitprice:" + unitPrice
				+ " qty:" + qtyindemand + " netprice" + netprice;
		return string;
	}

}
