package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerDebtortransaction generated by hbm2java
 */
public class VtigerDebtortransaction implements java.io.Serializable {

	private int transactionid;
	private String date;
	private Integer storeid;
	private Integer userid;
	private String username;
	private String openingbalance;
	private Integer invid;
	private String invNo;
	private String grandtotal;
	private String amtReceivedByCash;
	private String amtReceivedByCard;
	private String amtReceivedByCheck;
	private Integer salesretId;
	private String amtReturn;
	private String modeOfPayment;
	private String bankName;
	private String checkno;
	private String checkDate;
	private String balance;
	private String adjustment;
	private String refInvNo;
	private String closingbalance;
	private String modulename;

	public VtigerDebtortransaction() {
	}

	public VtigerDebtortransaction(int transactionid) {
		this.transactionid = transactionid;
	}

	public VtigerDebtortransaction(int transactionid, String date,
			Integer storeid, Integer userid, String username,
			String openingbalance, Integer invid, String invNo,
			String grandtotal, String amtReceivedByCash,
			String amtReceivedByCard, String amtReceivedByCheck,
			Integer salesretId, String amtReturn, String modeOfPayment,
			String bankName, String checkno, String checkDate, String balance,
			String adjustment, String refInvNo, String closingbalance,
			String modulename) {
		this.transactionid = transactionid;
		this.date = date;
		this.storeid = storeid;
		this.userid = userid;
		this.username = username;
		this.openingbalance = openingbalance;
		this.invid = invid;
		this.invNo = invNo;
		this.grandtotal = grandtotal;
		this.amtReceivedByCash = amtReceivedByCash;
		this.amtReceivedByCard = amtReceivedByCard;
		this.amtReceivedByCheck = amtReceivedByCheck;
		this.salesretId = salesretId;
		this.amtReturn = amtReturn;
		this.modeOfPayment = modeOfPayment;
		this.bankName = bankName;
		this.checkno = checkno;
		this.checkDate = checkDate;
		this.balance = balance;
		this.adjustment = adjustment;
		this.refInvNo = refInvNo;
		this.closingbalance = closingbalance;
		this.modulename = modulename;
	}

	public int getTransactionid() {
		return this.transactionid;
	}

	public void setTransactionid(int transactionid) {
		this.transactionid = transactionid;
	}

	public String getDate() {
		return this.date;
	}

	public void setDate(String date) {
		this.date = date;
	}

	public Integer getStoreid() {
		return this.storeid;
	}

	public void setStoreid(Integer storeid) {
		this.storeid = storeid;
	}

	public Integer getUserid() {
		return this.userid;
	}

	public void setUserid(Integer userid) {
		this.userid = userid;
	}

	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	public String getOpeningbalance() {
		return this.openingbalance;
	}

	public void setOpeningbalance(String openingbalance) {
		this.openingbalance = openingbalance;
	}

	public Integer getInvid() {
		return this.invid;
	}

	public void setInvid(Integer invid) {
		this.invid = invid;
	}

	public String getInvNo() {
		return this.invNo;
	}

	public void setInvNo(String invNo) {
		this.invNo = invNo;
	}

	public String getGrandtotal() {
		return this.grandtotal;
	}

	public void setGrandtotal(String grandtotal) {
		this.grandtotal = grandtotal;
	}

	public String getAmtReceivedByCash() {
		return this.amtReceivedByCash;
	}

	public void setAmtReceivedByCash(String amtReceivedByCash) {
		this.amtReceivedByCash = amtReceivedByCash;
	}

	public String getAmtReceivedByCard() {
		return this.amtReceivedByCard;
	}

	public void setAmtReceivedByCard(String amtReceivedByCard) {
		this.amtReceivedByCard = amtReceivedByCard;
	}

	public String getAmtReceivedByCheck() {
		return this.amtReceivedByCheck;
	}

	public void setAmtReceivedByCheck(String amtReceivedByCheck) {
		this.amtReceivedByCheck = amtReceivedByCheck;
	}

	public Integer getSalesretId() {
		return this.salesretId;
	}

	public void setSalesretId(Integer salesretId) {
		this.salesretId = salesretId;
	}

	public String getAmtReturn() {
		return this.amtReturn;
	}

	public void setAmtReturn(String amtReturn) {
		this.amtReturn = amtReturn;
	}

	public String getModeOfPayment() {
		return this.modeOfPayment;
	}

	public void setModeOfPayment(String modeOfPayment) {
		this.modeOfPayment = modeOfPayment;
	}

	public String getBankName() {
		return this.bankName;
	}

	public void setBankName(String bankName) {
		this.bankName = bankName;
	}

	public String getCheckno() {
		return this.checkno;
	}

	public void setCheckno(String checkno) {
		this.checkno = checkno;
	}

	public String getCheckDate() {
		return this.checkDate;
	}

	public void setCheckDate(String checkDate) {
		this.checkDate = checkDate;
	}

	public String getBalance() {
		return this.balance;
	}

	public void setBalance(String balance) {
		this.balance = balance;
	}

	public String getAdjustment() {
		return this.adjustment;
	}

	public void setAdjustment(String adjustment) {
		this.adjustment = adjustment;
	}

	public String getRefInvNo() {
		return this.refInvNo;
	}

	public void setRefInvNo(String refInvNo) {
		this.refInvNo = refInvNo;
	}

	public String getClosingbalance() {
		return this.closingbalance;
	}

	public void setClosingbalance(String closingbalance) {
		this.closingbalance = closingbalance;
	}

	public String getModulename() {
		return this.modulename;
	}

	public void setModulename(String modulename) {
		this.modulename = modulename;
	}

}
