package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerReports generated by hbm2java
 */
public class VtigerReports implements java.io.Serializable {

	private int id;
	private String reportCode;
	private String reportName;
	private String modName;
	private String isDeleted;

	public VtigerReports() {
	}

	public VtigerReports(int id, String reportCode, String reportName,
			String modName, String isDeleted) {
		this.id = id;
		this.reportCode = reportCode;
		this.reportName = reportName;
		this.modName = modName;
		this.isDeleted = isDeleted;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getReportCode() {
		return this.reportCode;
	}

	public void setReportCode(String reportCode) {
		this.reportCode = reportCode;
	}

	public String getReportName() {
		return this.reportName;
	}

	public void setReportName(String reportName) {
		this.reportName = reportName;
	}

	public String getModName() {
		return this.modName;
	}

	public void setModName(String modName) {
		this.modName = modName;
	}

	public String getIsDeleted() {
		return this.isDeleted;
	}

	public void setIsDeleted(String isDeleted) {
		this.isDeleted = isDeleted;
	}

}
