package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInventoryshippingrel generated by hbm2java
 */
public class VtigerInventoryshippingrel implements java.io.Serializable {

	private VtigerInventoryshippingrelId id;

	public VtigerInventoryshippingrel() {
	}

	public VtigerInventoryshippingrel(VtigerInventoryshippingrelId id) {
		this.id = id;
	}

	public VtigerInventoryshippingrelId getId() {
		return this.id;
	}

	public void setId(VtigerInventoryshippingrelId id) {
		this.id = id;
	}

}
