package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCategorycf generated by hbm2java
 */
public class VtigerCategorycf implements java.io.Serializable {

	private int categoryid;

	public VtigerCategorycf() {
	}

	public VtigerCategorycf(int categoryid) {
		this.categoryid = categoryid;
	}

	public int getCategoryid() {
		return this.categoryid;
	}

	public void setCategoryid(int categoryid) {
		this.categoryid = categoryid;
	}

}
