package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUserModulePreferencesId generated by hbm2java
 */
public class VtigerUserModulePreferencesId implements java.io.Serializable {

	private int userid;
	private int tabid;

	public VtigerUserModulePreferencesId() {
	}

	public VtigerUserModulePreferencesId(int userid, int tabid) {
		this.userid = userid;
		this.tabid = tabid;
	}

	public int getUserid() {
		return this.userid;
	}

	public void setUserid(int userid) {
		this.userid = userid;
	}

	public int getTabid() {
		return this.tabid;
	}

	public void setTabid(int tabid) {
		this.tabid = tabid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerUserModulePreferencesId))
			return false;
		VtigerUserModulePreferencesId castOther = (VtigerUserModulePreferencesId) other;

		return (this.getUserid() == castOther.getUserid())
				&& (this.getTabid() == castOther.getTabid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getUserid();
		result = 37 * result + this.getTabid();
		return result;
	}

}
