package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCustomerportalFields generated by hbm2java
 */
public class VtigerCustomerportalFields implements java.io.Serializable {

	private VtigerCustomerportalFieldsId id;

	public VtigerCustomerportalFields() {
	}

	public VtigerCustomerportalFields(VtigerCustomerportalFieldsId id) {
		this.id = id;
	}

	public VtigerCustomerportalFieldsId getId() {
		return this.id;
	}

	public void setId(VtigerCustomerportalFieldsId id) {
		this.id = id;
	}

}
