package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerBarcodegrouprel generated by hbm2java
 */
public class VtigerBarcodegrouprel implements java.io.Serializable {

	private int barcodeid;
	private String groupname;

	public VtigerBarcodegrouprel() {
	}

	public VtigerBarcodegrouprel(int barcodeid) {
		this.barcodeid = barcodeid;
	}

	public VtigerBarcodegrouprel(int barcodeid, String groupname) {
		this.barcodeid = barcodeid;
		this.groupname = groupname;
	}

	public int getBarcodeid() {
		return this.barcodeid;
	}

	public void setBarcodeid(int barcodeid) {
		this.barcodeid = barcodeid;
	}

	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

}
