package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCrmentityrel generated by hbm2java
 */
public class VtigerCrmentityrel implements java.io.Serializable {

	private VtigerCrmentityrelId id;

	public VtigerCrmentityrel() {
	}

	public VtigerCrmentityrel(VtigerCrmentityrelId id) {
		this.id = id;
	}

	public VtigerCrmentityrelId getId() {
		return this.id;
	}

	public void setId(VtigerCrmentityrelId id) {
		this.id = id;
	}

}
