package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInvoicestatus generated by hbm2java
 */
public class VtigerInvoicestatus implements java.io.Serializable {

	private int invoicestatusid;
	private String invoicestatus;
	private int presence;
	private int picklistValueid;

	public VtigerInvoicestatus() {
	}

	public VtigerInvoicestatus(int invoicestatusid, String invoicestatus,
			int presence, int picklistValueid) {
		this.invoicestatusid = invoicestatusid;
		this.invoicestatus = invoicestatus;
		this.presence = presence;
		this.picklistValueid = picklistValueid;
	}

	public int getInvoicestatusid() {
		return this.invoicestatusid;
	}

	public void setInvoicestatusid(int invoicestatusid) {
		this.invoicestatusid = invoicestatusid;
	}

	public String getInvoicestatus() {
		return this.invoicestatus;
	}

	public void setInvoicestatus(String invoicestatus) {
		this.invoicestatus = invoicestatus;
	}

	public int getPresence() {
		return this.presence;
	}

	public void setPresence(int presence) {
		this.presence = presence;
	}

	public int getPicklistValueid() {
		return this.picklistValueid;
	}

	public void setPicklistValueid(int picklistValueid) {
		this.picklistValueid = picklistValueid;
	}

}
