package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCashreceiptgrouprel generated by hbm2java
 */
public class VtigerCashreceiptgrouprel implements java.io.Serializable {

	private int cashreceiptid;
	private String groupname;

	public VtigerCashreceiptgrouprel() {
	}

	public VtigerCashreceiptgrouprel(int cashreceiptid) {
		this.cashreceiptid = cashreceiptid;
	}

	public VtigerCashreceiptgrouprel(int cashreceiptid, String groupname) {
		this.cashreceiptid = cashreceiptid;
		this.groupname = groupname;
	}

	public int getCashreceiptid() {
		return this.cashreceiptid;
	}

	public void setCashreceiptid(int cashreceiptid) {
		this.cashreceiptid = cashreceiptid;
	}

	public String getGroupname() {
		return this.groupname;
	}

	public void setGroupname(String groupname) {
		this.groupname = groupname;
	}

}
