package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContractPriority generated by hbm2java
 */
public class VtigerContractPriority implements java.io.Serializable {

	private int contractPriorityid;
	private String contractPriority;
	private int presence;
	private int picklistValueid;

	public VtigerContractPriority() {
	}

	public VtigerContractPriority(int contractPriorityid,
			String contractPriority, int presence, int picklistValueid) {
		this.contractPriorityid = contractPriorityid;
		this.contractPriority = contractPriority;
		this.presence = presence;
		this.picklistValueid = picklistValueid;
	}

	public int getContractPriorityid() {
		return this.contractPriorityid;
	}

	public void setContractPriorityid(int contractPriorityid) {
		this.contractPriorityid = contractPriorityid;
	}

	public String getContractPriority() {
		return this.contractPriority;
	}

	public void setContractPriority(String contractPriority) {
		this.contractPriority = contractPriority;
	}

	public int getPresence() {
		return this.presence;
	}

	public void setPresence(int presence) {
		this.presence = presence;
	}

	public int getPicklistValueid() {
		return this.picklistValueid;
	}

	public void setPicklistValueid(int picklistValueid) {
		this.picklistValueid = picklistValueid;
	}

}
