package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCrmentitynotesrelId generated by hbm2java
 */
public class VtigerCrmentitynotesrelId implements java.io.Serializable {

	private int crmid;
	private int notesid;

	public VtigerCrmentitynotesrelId() {
	}

	public VtigerCrmentitynotesrelId(int crmid, int notesid) {
		this.crmid = crmid;
		this.notesid = notesid;
	}

	public int getCrmid() {
		return this.crmid;
	}

	public void setCrmid(int crmid) {
		this.crmid = crmid;
	}

	public int getNotesid() {
		return this.notesid;
	}

	public void setNotesid(int notesid) {
		this.notesid = notesid;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerCrmentitynotesrelId))
			return false;
		VtigerCrmentitynotesrelId castOther = (VtigerCrmentitynotesrelId) other;

		return (this.getCrmid() == castOther.getCrmid())
				&& (this.getNotesid() == castOther.getNotesid());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getCrmid();
		result = 37 * result + this.getNotesid();
		return result;
	}

}
