package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCashreceipt generated by hbm2java
 */
public class VtigerCashreceipt implements java.io.Serializable {

	private VtigerCashreceiptId id;

	public VtigerCashreceipt() {
	}

	public VtigerCashreceipt(VtigerCashreceiptId id) {
		this.id = id;
	}

	public VtigerCashreceipt(int cash_id, int new_crmid, int cusid,
			String grandtotal, String credit_amount, String paidamount,
			String pendingamount, String dateTime) {
		// TODO Auto-generated constructor stub
	}

	public VtigerCashreceiptId getId() {
		return this.id;
	}

	public void setId(VtigerCashreceiptId id) {
		this.id = id;
	}

}
