package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInvoicestatushistory generated by hbm2java
 */
public class VtigerInvoicestatushistory implements java.io.Serializable {

	private int historyid;
	private int invoiceid;
	private String accountname;
	private String total;
	private String invoicestatus;
	private String lastmodified;

	public VtigerInvoicestatushistory() {
	}

	public VtigerInvoicestatushistory(int historyid, int invoiceid) {
		this.historyid = historyid;
		this.invoiceid = invoiceid;
	}

	public VtigerInvoicestatushistory(int historyid, int invoiceid,
			String accountname, String total, String invoicestatus,
			String lastmodified) {
		this.historyid = historyid;
		this.invoiceid = invoiceid;
		this.accountname = accountname;
		this.total = total;
		this.invoicestatus = invoicestatus;
		this.lastmodified = lastmodified;
	}

	public int getHistoryid() {
		return this.historyid;
	}

	public void setHistoryid(int historyid) {
		this.historyid = historyid;
	}

	public int getInvoiceid() {
		return this.invoiceid;
	}

	public void setInvoiceid(int invoiceid) {
		this.invoiceid = invoiceid;
	}

	public String getAccountname() {
		return this.accountname;
	}

	public void setAccountname(String accountname) {
		this.accountname = accountname;
	}

	public String getTotal() {
		return this.total;
	}

	public void setTotal(String total) {
		this.total = total;
	}

	public String getInvoicestatus() {
		return this.invoicestatus;
	}

	public void setInvoicestatus(String invoicestatus) {
		this.invoicestatus = invoicestatus;
	}

	public String getLastmodified() {
		return this.lastmodified;
	}

	public void setLastmodified(String lastmodified) {
		this.lastmodified = lastmodified;
	}

}
