package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContactsubdetails generated by hbm2java
 */
public class VtigerContactsubdetails implements java.io.Serializable {

	private int contactsubscriptionid;
	private String homephone;
	private String otherphone;
	private String assistant;
	private String assistantphone;
	private String birthday;
	private Integer laststayintouchrequest;
	private Integer laststayintouchsavedate;
	private String leadsource;

	public VtigerContactsubdetails() {
	}

	public VtigerContactsubdetails(int contactsubscriptionid) {
		this.contactsubscriptionid = contactsubscriptionid;
	}

	public VtigerContactsubdetails(int contactsubscriptionid, String homephone,
			String otherphone, String assistant, String assistantphone,
			String birthday, Integer laststayintouchrequest,
			Integer laststayintouchsavedate, String leadsource) {
		this.contactsubscriptionid = contactsubscriptionid;
		this.homephone = homephone;
		this.otherphone = otherphone;
		this.assistant = assistant;
		this.assistantphone = assistantphone;
		this.birthday = birthday;
		this.laststayintouchrequest = laststayintouchrequest;
		this.laststayintouchsavedate = laststayintouchsavedate;
		this.leadsource = leadsource;
	}

	public int getContactsubscriptionid() {
		return this.contactsubscriptionid;
	}

	public void setContactsubscriptionid(int contactsubscriptionid) {
		this.contactsubscriptionid = contactsubscriptionid;
	}

	public String getHomephone() {
		return this.homephone;
	}

	public void setHomephone(String homephone) {
		this.homephone = homephone;
	}

	public String getOtherphone() {
		return this.otherphone;
	}

	public void setOtherphone(String otherphone) {
		this.otherphone = otherphone;
	}

	public String getAssistant() {
		return this.assistant;
	}

	public void setAssistant(String assistant) {
		this.assistant = assistant;
	}

	public String getAssistantphone() {
		return this.assistantphone;
	}

	public void setAssistantphone(String assistantphone) {
		this.assistantphone = assistantphone;
	}

	public String getBirthday() {
		return this.birthday;
	}

	public void setBirthday(String birthday) {
		this.birthday = birthday;
	}

	public Integer getLaststayintouchrequest() {
		return this.laststayintouchrequest;
	}

	public void setLaststayintouchrequest(Integer laststayintouchrequest) {
		this.laststayintouchrequest = laststayintouchrequest;
	}

	public Integer getLaststayintouchsavedate() {
		return this.laststayintouchsavedate;
	}

	public void setLaststayintouchsavedate(Integer laststayintouchsavedate) {
		this.laststayintouchsavedate = laststayintouchsavedate;
	}

	public String getLeadsource() {
		return this.leadsource;
	}

	public void setLeadsource(String leadsource) {
		this.leadsource = leadsource;
	}

}
