package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCategory generated by hbm2java
 */
public class VtigerCategory implements java.io.Serializable {

	private VtigerCategoryId id;
	private String taxtype;
	private String vat;
	private String size;
	private String color;

	public VtigerCategory() {
	}

	public VtigerCategory(VtigerCategoryId id, String taxtype) {
		this.id = id;
		this.taxtype = taxtype;
	}

	public VtigerCategory(VtigerCategoryId id, String taxtype, String vat,
			String size, String color) {
		this.id = id;
		this.taxtype = taxtype;
		this.vat = vat;
		this.size = size;
		this.color = color;
	}

	public VtigerCategoryId getId() {
		return this.id;
	}

	public void setId(VtigerCategoryId id) {
		this.id = id;
	}

	public String getTaxtype() {
		return this.taxtype;
	}

	public void setTaxtype(String taxtype) {
		this.taxtype = taxtype;
	}

	public String getVat() {
		return this.vat;
	}

	public void setVat(String vat) {
		this.vat = vat;
	}

	public String getSize() {
		return this.size;
	}

	public void setSize(String size) {
		this.size = size;
	}

	public String getColor() {
		return this.color;
	}

	public void setColor(String color) {
		this.color = color;
	}

}
