package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInvoiceshipads generated by hbm2java
 */
public class VtigerInvoiceshipads implements java.io.Serializable {

	private int invoiceshipaddressid;
	private String shipCity;
	private String shipCode;
	private String shipCountry;
	private String shipState;
	private String shipStreet;
	private String shipPobox;

	public VtigerInvoiceshipads() {
	}

	public VtigerInvoiceshipads(int invoiceshipaddressid) {
		this.invoiceshipaddressid = invoiceshipaddressid;
	}

	public VtigerInvoiceshipads(int invoiceshipaddressid, String shipCity,
			String shipCode, String shipCountry, String shipState,
			String shipStreet, String shipPobox) {
		this.invoiceshipaddressid = invoiceshipaddressid;
		this.shipCity = shipCity;
		this.shipCode = shipCode;
		this.shipCountry = shipCountry;
		this.shipState = shipState;
		this.shipStreet = shipStreet;
		this.shipPobox = shipPobox;
	}

	public int getInvoiceshipaddressid() {
		return this.invoiceshipaddressid;
	}

	public void setInvoiceshipaddressid(int invoiceshipaddressid) {
		this.invoiceshipaddressid = invoiceshipaddressid;
	}

	public String getShipCity() {
		return this.shipCity;
	}

	public void setShipCity(String shipCity) {
		this.shipCity = shipCity;
	}

	public String getShipCode() {
		return this.shipCode;
	}

	public void setShipCode(String shipCode) {
		this.shipCode = shipCode;
	}

	public String getShipCountry() {
		return this.shipCountry;
	}

	public void setShipCountry(String shipCountry) {
		this.shipCountry = shipCountry;
	}

	public String getShipState() {
		return this.shipState;
	}

	public void setShipState(String shipState) {
		this.shipState = shipState;
	}

	public String getShipStreet() {
		return this.shipStreet;
	}

	public void setShipStreet(String shipStreet) {
		this.shipStreet = shipStreet;
	}

	public String getShipPobox() {
		return this.shipPobox;
	}

	public void setShipPobox(String shipPobox) {
		this.shipPobox = shipPobox;
	}

}
