package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerProductcategory generated by hbm2java
 */
public class VtigerProductcategory implements java.io.Serializable {

	private int productcategoryid;
	private String productcategory;
	private int presence;
	private int picklistValueid;

	public VtigerProductcategory() {
	}

	public VtigerProductcategory(int productcategoryid, String productcategory,
			int presence, int picklistValueid) {
		this.productcategoryid = productcategoryid;
		this.productcategory = productcategory;
		this.presence = presence;
		this.picklistValueid = picklistValueid;
	}

	public int getProductcategoryid() {
		return this.productcategoryid;
	}

	public void setProductcategoryid(int productcategoryid) {
		this.productcategoryid = productcategoryid;
	}

	public String getProductcategory() {
		return this.productcategory;
	}

	public void setProductcategory(String productcategory) {
		this.productcategory = productcategory;
	}

	public int getPresence() {
		return this.presence;
	}

	public void setPresence(int presence) {
		this.presence = presence;
	}

	public int getPicklistValueid() {
		return this.picklistValueid;
	}

	public void setPicklistValueid(int picklistValueid) {
		this.picklistValueid = picklistValueid;
	}

}
