package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUsersLastImport generated by hbm2java
 */
public class VtigerUsersLastImport implements java.io.Serializable {

	private int id;
	private String assignedUserId;
	private String beanType;
	private String beanId;
	private int deleted;

	public VtigerUsersLastImport() {
	}

	public VtigerUsersLastImport(int id, int deleted) {
		this.id = id;
		this.deleted = deleted;
	}

	public VtigerUsersLastImport(int id, String assignedUserId,
			String beanType, String beanId, int deleted) {
		this.id = id;
		this.assignedUserId = assignedUserId;
		this.beanType = beanType;
		this.beanId = beanId;
		this.deleted = deleted;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getAssignedUserId() {
		return this.assignedUserId;
	}

	public void setAssignedUserId(String assignedUserId) {
		this.assignedUserId = assignedUserId;
	}

	public String getBeanType() {
		return this.beanType;
	}

	public void setBeanType(String beanType) {
		this.beanType = beanType;
	}

	public String getBeanId() {
		return this.beanId;
	}

	public void setBeanId(String beanId) {
		this.beanId = beanId;
	}

	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

}
