package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUserModulePreferences generated by hbm2java
 */
public class VtigerUserModulePreferences implements java.io.Serializable {

	private VtigerUserModulePreferencesId id;
	private int defaultCvid;

	public VtigerUserModulePreferences() {
	}

	public VtigerUserModulePreferences(VtigerUserModulePreferencesId id,
			int defaultCvid) {
		this.id = id;
		this.defaultCvid = defaultCvid;
	}

	public VtigerUserModulePreferencesId getId() {
		return this.id;
	}

	public void setId(VtigerUserModulePreferencesId id) {
		this.id = id;
	}

	public int getDefaultCvid() {
		return this.defaultCvid;
	}

	public void setDefaultCvid(int defaultCvid) {
		this.defaultCvid = defaultCvid;
	}

}
