package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerProductcollaterals generated by hbm2java
 */
public class VtigerProductcollaterals implements java.io.Serializable {

	private int productid;
	private String dateEntered;
	private String data;
	private String description;
	private String filename;
	private String filesize;
	private String filetype;

	public VtigerProductcollaterals() {
	}

	public VtigerProductcollaterals(int productid, String dateEntered,
			String filesize, String filetype) {
		this.productid = productid;
		this.dateEntered = dateEntered;
		this.filesize = filesize;
		this.filetype = filetype;
	}

	public VtigerProductcollaterals(int productid, String dateEntered,
			String data, String description, String filename, String filesize,
			String filetype) {
		this.productid = productid;
		this.dateEntered = dateEntered;
		this.data = data;
		this.description = description;
		this.filename = filename;
		this.filesize = filesize;
		this.filetype = filetype;
	}

	public int getProductid() {
		return this.productid;
	}

	public void setProductid(int productid) {
		this.productid = productid;
	}

	public String getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(String dateEntered) {
		this.dateEntered = dateEntered;
	}

	public String getData() {
		return this.data;
	}

	public void setData(String data) {
		this.data = data;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getFilename() {
		return this.filename;
	}

	public void setFilename(String filename) {
		this.filename = filename;
	}

	public String getFilesize() {
		return this.filesize;
	}

	public void setFilesize(String filesize) {
		this.filesize = filesize;
	}

	public String getFiletype() {
		return this.filetype;
	}

	public void setFiletype(String filetype) {
		this.filetype = filetype;
	}

}
