package com.vendhaq.models;

// Generated Dec 13, 2012 3:37:45 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.Date;

/**
 * VtigerRoyalityAmount generated by hbm2java
 */
public class VtigerRoyalityAmount implements java.io.Serializable {

	private int id;
	private int royalityCount;
	private BigDecimal royalityamount;
	private Date fromDate;
	private Date toDate;

	public VtigerRoyalityAmount() {
	}

	public VtigerRoyalityAmount(int id, int royalityCount, BigDecimal royalityamount) {
		this.id = id;
		this.royalityCount = royalityCount;
		this.royalityamount = royalityamount;
	}

	public VtigerRoyalityAmount(int id, int royalityCount, BigDecimal royalityamount, Date fromDate, Date toDate) {
		this.id = id;
		this.royalityCount = royalityCount;
		this.royalityamount = royalityamount;
		this.fromDate = fromDate;
		this.toDate = toDate;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public int getRoyalityCount() {
		return this.royalityCount;
	}

	public void setRoyalityCount(int royalityCount) {
		this.royalityCount = royalityCount;
	}

	public BigDecimal getRoyalityamount() {
		return this.royalityamount;
	}

	public void setRoyalityamount(BigDecimal royalityamount) {
		this.royalityamount = royalityamount;
	}

	public Date getFromDate() {
		return this.fromDate;
	}

	public void setFromDate(Date fromDate) {
		this.fromDate = fromDate;
	}

	public Date getToDate() {
		return this.toDate;
	}

	public void setToDate(Date toDate) {
		this.toDate = toDate;
	}

}
