package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUser2mergefields generated by hbm2java
 */
public class VtigerUser2mergefields implements java.io.Serializable {

	private VtigerUser2mergefieldsId id;

	public VtigerUser2mergefields() {
	}

	public VtigerUser2mergefields(VtigerUser2mergefieldsId id) {
		this.id = id;
	}

	public VtigerUser2mergefieldsId getId() {
		return this.id;
	}

	public void setId(VtigerUser2mergefieldsId id) {
		this.id = id;
	}

}
