package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerCrmentitynotesrel generated by hbm2java
 */
public class VtigerCrmentitynotesrel implements java.io.Serializable {

	private VtigerCrmentitynotesrelId id;

	public VtigerCrmentitynotesrel() {
	}

	public VtigerCrmentitynotesrel(VtigerCrmentitynotesrelId id) {
		this.id = id;
	}

	public VtigerCrmentitynotesrelId getId() {
		return this.id;
	}

	public void setId(VtigerCrmentitynotesrelId id) {
		this.id = id;
	}

}
