package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInventorytaxinfo generated by hbm2java
 */
public class VtigerInventorytaxinfo implements java.io.Serializable {

	private int taxid;
	private String taxname;
	private String taxlabel;
	private String percentage;
	private Integer deleted;

	public VtigerInventorytaxinfo() {
	}

	public VtigerInventorytaxinfo(int taxid) {
		this.taxid = taxid;
	}

	public VtigerInventorytaxinfo(int taxid, String taxname, String taxlabel,
			String percentage, Integer deleted) {
		this.taxid = taxid;
		this.taxname = taxname;
		this.taxlabel = taxlabel;
		this.percentage = percentage;
		this.deleted = deleted;
	}

	public int getTaxid() {
		return this.taxid;
	}

	public void setTaxid(int taxid) {
		this.taxid = taxid;
	}

	public String getTaxname() {
		return this.taxname;
	}

	public void setTaxname(String taxname) {
		this.taxname = taxname;
	}

	public String getTaxlabel() {
		return this.taxlabel;
	}

	public void setTaxlabel(String taxlabel) {
		this.taxlabel = taxlabel;
	}

	public String getPercentage() {
		return this.percentage;
	}

	public void setPercentage(String percentage) {
		this.percentage = percentage;
	}

	public Integer getDeleted() {
		return this.deleted;
	}

	public void setDeleted(Integer deleted) {
		this.deleted = deleted;
	}

}
