package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerInvoiceRecurringInfoId generated by hbm2java
 */
public class VtigerInvoiceRecurringInfoId implements java.io.Serializable {

	private Integer salesorderid;
	private String recurringFrequency;
	private String startPeriod;
	private String endPeriod;
	private String lastRecurringDate;
	private String paymentDuration;
	private String invoiceStatus;

	public VtigerInvoiceRecurringInfoId() {
	}

	public VtigerInvoiceRecurringInfoId(Integer salesorderid,
			String recurringFrequency, String startPeriod, String endPeriod,
			String lastRecurringDate, String paymentDuration,
			String invoiceStatus) {
		this.salesorderid = salesorderid;
		this.recurringFrequency = recurringFrequency;
		this.startPeriod = startPeriod;
		this.endPeriod = endPeriod;
		this.lastRecurringDate = lastRecurringDate;
		this.paymentDuration = paymentDuration;
		this.invoiceStatus = invoiceStatus;
	}

	public Integer getSalesorderid() {
		return this.salesorderid;
	}

	public void setSalesorderid(Integer salesorderid) {
		this.salesorderid = salesorderid;
	}

	public String getRecurringFrequency() {
		return this.recurringFrequency;
	}

	public void setRecurringFrequency(String recurringFrequency) {
		this.recurringFrequency = recurringFrequency;
	}

	public String getStartPeriod() {
		return this.startPeriod;
	}

	public void setStartPeriod(String startPeriod) {
		this.startPeriod = startPeriod;
	}

	public String getEndPeriod() {
		return this.endPeriod;
	}

	public void setEndPeriod(String endPeriod) {
		this.endPeriod = endPeriod;
	}

	public String getLastRecurringDate() {
		return this.lastRecurringDate;
	}

	public void setLastRecurringDate(String lastRecurringDate) {
		this.lastRecurringDate = lastRecurringDate;
	}

	public String getPaymentDuration() {
		return this.paymentDuration;
	}

	public void setPaymentDuration(String paymentDuration) {
		this.paymentDuration = paymentDuration;
	}

	public String getInvoiceStatus() {
		return this.invoiceStatus;
	}

	public void setInvoiceStatus(String invoiceStatus) {
		this.invoiceStatus = invoiceStatus;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof VtigerInvoiceRecurringInfoId))
			return false;
		VtigerInvoiceRecurringInfoId castOther = (VtigerInvoiceRecurringInfoId) other;

		return ((this.getSalesorderid() == castOther.getSalesorderid()) || (this
				.getSalesorderid() != null
				&& castOther.getSalesorderid() != null && this
				.getSalesorderid().equals(castOther.getSalesorderid())))
				&& ((this.getRecurringFrequency() == castOther
						.getRecurringFrequency()) || (this
						.getRecurringFrequency() != null
						&& castOther.getRecurringFrequency() != null && this
						.getRecurringFrequency().equals(
								castOther.getRecurringFrequency())))
				&& ((this.getStartPeriod() == castOther.getStartPeriod()) || (this
						.getStartPeriod() != null
						&& castOther.getStartPeriod() != null && this
						.getStartPeriod().equals(castOther.getStartPeriod())))
				&& ((this.getEndPeriod() == castOther.getEndPeriod()) || (this
						.getEndPeriod() != null
						&& castOther.getEndPeriod() != null && this
						.getEndPeriod().equals(castOther.getEndPeriod())))
				&& ((this.getLastRecurringDate() == castOther
						.getLastRecurringDate()) || (this
						.getLastRecurringDate() != null
						&& castOther.getLastRecurringDate() != null && this
						.getLastRecurringDate().equals(
								castOther.getLastRecurringDate())))
				&& ((this.getPaymentDuration() == castOther
						.getPaymentDuration()) || (this.getPaymentDuration() != null
						&& castOther.getPaymentDuration() != null && this
						.getPaymentDuration().equals(
								castOther.getPaymentDuration())))
				&& ((this.getInvoiceStatus() == castOther.getInvoiceStatus()) || (this
						.getInvoiceStatus() != null
						&& castOther.getInvoiceStatus() != null && this
						.getInvoiceStatus()
						.equals(castOther.getInvoiceStatus())));
	}

	public int hashCode() {
		int result = 17;

		result = 37
				* result
				+ (getSalesorderid() == null ? 0 : this.getSalesorderid()
						.hashCode());
		result = 37
				* result
				+ (getRecurringFrequency() == null ? 0 : this
						.getRecurringFrequency().hashCode());
		result = 37
				* result
				+ (getStartPeriod() == null ? 0 : this.getStartPeriod()
						.hashCode());
		result = 37 * result
				+ (getEndPeriod() == null ? 0 : this.getEndPeriod().hashCode());
		result = 37
				* result
				+ (getLastRecurringDate() == null ? 0 : this
						.getLastRecurringDate().hashCode());
		result = 37
				* result
				+ (getPaymentDuration() == null ? 0 : this.getPaymentDuration()
						.hashCode());
		result = 37
				* result
				+ (getInvoiceStatus() == null ? 0 : this.getInvoiceStatus()
						.hashCode());
		return result;
	}

}
