package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerContactdetails generated by hbm2java
 */
public class VtigerContactdetails implements java.io.Serializable {

	private int contactid;
	private String contactNo;
	private Integer accountid;
	private String salutation;
	private String firstname;
	private String lastname;
	private String email;
	private String phone;
	private String mobile;
	private String title;
	private String department;
	private String fax;
	private String reportsto;
	private String training;
	private String usertype;
	private String contacttype;
	private String otheremail;
	private String yahooid;
	private String donotcall;
	private String emailoptout;
	private String imagename;
	private String reference;
	private String notifyOwner;

	public VtigerContactdetails() {
	}

	public VtigerContactdetails(int contactid, String contactNo, String lastname) {
		this.contactid = contactid;
		this.contactNo = contactNo;
		this.lastname = lastname;
	}

	public VtigerContactdetails(int contactid, String contactNo,
			Integer accountid, String salutation, String firstname,
			String lastname, String email, String phone, String mobile,
			String title, String department, String fax, String reportsto,
			String training, String usertype, String contacttype,
			String otheremail, String yahooid, String donotcall,
			String emailoptout, String imagename, String reference,
			String notifyOwner) {
		this.contactid = contactid;
		this.contactNo = contactNo;
		this.accountid = accountid;
		this.salutation = salutation;
		this.firstname = firstname;
		this.lastname = lastname;
		this.email = email;
		this.phone = phone;
		this.mobile = mobile;
		this.title = title;
		this.department = department;
		this.fax = fax;
		this.reportsto = reportsto;
		this.training = training;
		this.usertype = usertype;
		this.contacttype = contacttype;
		this.otheremail = otheremail;
		this.yahooid = yahooid;
		this.donotcall = donotcall;
		this.emailoptout = emailoptout;
		this.imagename = imagename;
		this.reference = reference;
		this.notifyOwner = notifyOwner;
	}

	public VtigerContactdetails(int contactid, String contactNo,
			String firstname, String lastname, String mobile, String email, String usertype) {
		this.contactid = contactid;
		this.contactNo = contactNo;
		this.firstname = firstname;
		this.lastname = lastname;
		this.mobile = mobile;
		this.email = email;
		this.usertype = usertype;
	}

	public int getContactid() {
		return this.contactid;
	}

	public void setContactid(int contactid) {
		this.contactid = contactid;
	}

	public String getContactNo() {
		return this.contactNo;
	}

	public void setContactNo(String contactNo) {
		this.contactNo = contactNo;
	}

	public Integer getAccountid() {
		return this.accountid;
	}

	public void setAccountid(Integer accountid) {
		this.accountid = accountid;
	}

	public String getSalutation() {
		return this.salutation;
	}

	public void setSalutation(String salutation) {
		this.salutation = salutation;
	}

	public String getFirstname() {
		return this.firstname;
	}

	public void setFirstname(String firstname) {
		this.firstname = firstname;
	}

	public String getLastname() {
		return this.lastname;
	}

	public void setLastname(String lastname) {
		this.lastname = lastname;
	}

	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	public String getPhone() {
		return this.phone;
	}

	public void setPhone(String phone) {
		this.phone = phone;
	}

	public String getMobile() {
		return this.mobile;
	}

	public void setMobile(String mobile) {
		this.mobile = mobile;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getFax() {
		return this.fax;
	}

	public void setFax(String fax) {
		this.fax = fax;
	}

	public String getReportsto() {
		return this.reportsto;
	}

	public void setReportsto(String reportsto) {
		this.reportsto = reportsto;
	}

	public String getTraining() {
		return this.training;
	}

	public void setTraining(String training) {
		this.training = training;
	}

	public String getUsertype() {
		return this.usertype;
	}

	public void setUsertype(String usertype) {
		this.usertype = usertype;
	}

	public String getContacttype() {
		return this.contacttype;
	}

	public void setContacttype(String contacttype) {
		this.contacttype = contacttype;
	}

	public String getOtheremail() {
		return this.otheremail;
	}

	public void setOtheremail(String otheremail) {
		this.otheremail = otheremail;
	}

	public String getYahooid() {
		return this.yahooid;
	}

	public void setYahooid(String yahooid) {
		this.yahooid = yahooid;
	}

	public String getDonotcall() {
		return this.donotcall;
	}

	public void setDonotcall(String donotcall) {
		this.donotcall = donotcall;
	}

	public String getEmailoptout() {
		return this.emailoptout;
	}

	public void setEmailoptout(String emailoptout) {
		this.emailoptout = emailoptout;
	}

	public String getImagename() {
		return this.imagename;
	}

	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	public String getReference() {
		return this.reference;
	}

	public void setReference(String reference) {
		this.reference = reference;
	}

	public String getNotifyOwner() {
		return this.notifyOwner;
	}

	public void setNotifyOwner(String notifyOwner) {
		this.notifyOwner = notifyOwner;
	}

}
