package com.vendhaq.models;

// Generated Nov 17, 2012 10:58:25 AM by Hibernate Tools 3.4.0.CR1

/**
 * VtigerUsers generated by hbm2java
 */
public class VtigerUsers implements java.io.Serializable {

	private int id;
	private String userName;
	private String userPassword;
	private String userHash;
	private String calColor;
	private String firstName;
	private String lastName;
	private String reportsToId;
	private String isAdmin;
	private int currencyId;
	private String description;
	private String dateEntered;
	private String dateModified;
	private String modifiedUserId;
	private String title;
	private String department;
	private String phoneHome;
	private String phoneMobile;
	private String phoneWork;
	private String phoneOther;
	private String phoneFax;
	private String email1;
	private String email2;
	private String yahooId;
	private String status;
	private String signature;
	private String addressStreet;
	private String addressCity;
	private String addressState;
	private String addressCountry;
	private String addressPostalcode;
	private String userPreferences;
	private String tz;
	private String holidays;
	private String namedays;
	private String workdays;
	private Integer weekstart;
	private String dateFormat;
	private String hourFormat;
	private String startHour;
	private String endHour;
	private String activityView;
	private String leadView;
	private String imagename;
	private int deleted;
	private String confirmPassword;
	private String internalMailer;
	private String reminderInterval;
	private String reminderNextTime;
	private String cryptType;
	private String accesskey;

	public VtigerUsers() {
	}

	public VtigerUsers(int id, int currencyId, String dateEntered,
			String dateModified, int deleted, String internalMailer,
			String cryptType) {
		this.id = id;
		this.currencyId = currencyId;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.deleted = deleted;
		this.internalMailer = internalMailer;
		this.cryptType = cryptType;
	}

	public VtigerUsers(int id, String userName, String userPassword,
			String userHash, String calColor, String firstName,
			String lastName, String reportsToId, String isAdmin,
			int currencyId, String description, String dateEntered,
			String dateModified, String modifiedUserId, String title,
			String department, String phoneHome, String phoneMobile,
			String phoneWork, String phoneOther, String phoneFax,
			String email1, String email2, String yahooId, String status,
			String signature, String addressStreet, String addressCity,
			String addressState, String addressCountry,
			String addressPostalcode, String userPreferences, String tz,
			String holidays, String namedays, String workdays,
			Integer weekstart, String dateFormat, String hourFormat,
			String startHour, String endHour, String activityView,
			String leadView, String imagename, int deleted,
			String confirmPassword, String internalMailer,
			String reminderInterval, String reminderNextTime, String cryptType,
			String accesskey) {
		this.id = id;
		this.userName = userName;
		this.userPassword = userPassword;
		this.userHash = userHash;
		this.calColor = calColor;
		this.firstName = firstName;
		this.lastName = lastName;
		this.reportsToId = reportsToId;
		this.isAdmin = isAdmin;
		this.currencyId = currencyId;
		this.description = description;
		this.dateEntered = dateEntered;
		this.dateModified = dateModified;
		this.modifiedUserId = modifiedUserId;
		this.title = title;
		this.department = department;
		this.phoneHome = phoneHome;
		this.phoneMobile = phoneMobile;
		this.phoneWork = phoneWork;
		this.phoneOther = phoneOther;
		this.phoneFax = phoneFax;
		this.email1 = email1;
		this.email2 = email2;
		this.yahooId = yahooId;
		this.status = status;
		this.signature = signature;
		this.addressStreet = addressStreet;
		this.addressCity = addressCity;
		this.addressState = addressState;
		this.addressCountry = addressCountry;
		this.addressPostalcode = addressPostalcode;
		this.userPreferences = userPreferences;
		this.tz = tz;
		this.holidays = holidays;
		this.namedays = namedays;
		this.workdays = workdays;
		this.weekstart = weekstart;
		this.dateFormat = dateFormat;
		this.hourFormat = hourFormat;
		this.startHour = startHour;
		this.endHour = endHour;
		this.activityView = activityView;
		this.leadView = leadView;
		this.imagename = imagename;
		this.deleted = deleted;
		this.confirmPassword = confirmPassword;
		this.internalMailer = internalMailer;
		this.reminderInterval = reminderInterval;
		this.reminderNextTime = reminderNextTime;
		this.cryptType = cryptType;
		this.accesskey = accesskey;
	}

	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	public String getUserName() {
		return this.userName;
	}

	public void setUserName(String userName) {
		this.userName = userName;
	}

	public String getUserPassword() {
		return this.userPassword;
	}

	public void setUserPassword(String userPassword) {
		this.userPassword = userPassword;
	}

	public String getUserHash() {
		return this.userHash;
	}

	public void setUserHash(String userHash) {
		this.userHash = userHash;
	}

	public String getCalColor() {
		return this.calColor;
	}

	public void setCalColor(String calColor) {
		this.calColor = calColor;
	}

	public String getFirstName() {
		return this.firstName;
	}

	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	public String getLastName() {
		return this.lastName;
	}

	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public String getReportsToId() {
		return this.reportsToId;
	}

	public void setReportsToId(String reportsToId) {
		this.reportsToId = reportsToId;
	}

	public String getIsAdmin() {
		return this.isAdmin;
	}

	public void setIsAdmin(String isAdmin) {
		this.isAdmin = isAdmin;
	}

	public int getCurrencyId() {
		return this.currencyId;
	}

	public void setCurrencyId(int currencyId) {
		this.currencyId = currencyId;
	}

	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

	public String getDateEntered() {
		return this.dateEntered;
	}

	public void setDateEntered(String dateEntered) {
		this.dateEntered = dateEntered;
	}

	public String getDateModified() {
		return this.dateModified;
	}

	public void setDateModified(String dateModified) {
		this.dateModified = dateModified;
	}

	public String getModifiedUserId() {
		return this.modifiedUserId;
	}

	public void setModifiedUserId(String modifiedUserId) {
		this.modifiedUserId = modifiedUserId;
	}

	public String getTitle() {
		return this.title;
	}

	public void setTitle(String title) {
		this.title = title;
	}

	public String getDepartment() {
		return this.department;
	}

	public void setDepartment(String department) {
		this.department = department;
	}

	public String getPhoneHome() {
		return this.phoneHome;
	}

	public void setPhoneHome(String phoneHome) {
		this.phoneHome = phoneHome;
	}

	public String getPhoneMobile() {
		return this.phoneMobile;
	}

	public void setPhoneMobile(String phoneMobile) {
		this.phoneMobile = phoneMobile;
	}

	public String getPhoneWork() {
		return this.phoneWork;
	}

	public void setPhoneWork(String phoneWork) {
		this.phoneWork = phoneWork;
	}

	public String getPhoneOther() {
		return this.phoneOther;
	}

	public void setPhoneOther(String phoneOther) {
		this.phoneOther = phoneOther;
	}

	public String getPhoneFax() {
		return this.phoneFax;
	}

	public void setPhoneFax(String phoneFax) {
		this.phoneFax = phoneFax;
	}

	public String getEmail1() {
		return this.email1;
	}

	public void setEmail1(String email1) {
		this.email1 = email1;
	}

	public String getEmail2() {
		return this.email2;
	}

	public void setEmail2(String email2) {
		this.email2 = email2;
	}

	public String getYahooId() {
		return this.yahooId;
	}

	public void setYahooId(String yahooId) {
		this.yahooId = yahooId;
	}

	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	public String getSignature() {
		return this.signature;
	}

	public void setSignature(String signature) {
		this.signature = signature;
	}

	public String getAddressStreet() {
		return this.addressStreet;
	}

	public void setAddressStreet(String addressStreet) {
		this.addressStreet = addressStreet;
	}

	public String getAddressCity() {
		return this.addressCity;
	}

	public void setAddressCity(String addressCity) {
		this.addressCity = addressCity;
	}

	public String getAddressState() {
		return this.addressState;
	}

	public void setAddressState(String addressState) {
		this.addressState = addressState;
	}

	public String getAddressCountry() {
		return this.addressCountry;
	}

	public void setAddressCountry(String addressCountry) {
		this.addressCountry = addressCountry;
	}

	public String getAddressPostalcode() {
		return this.addressPostalcode;
	}

	public void setAddressPostalcode(String addressPostalcode) {
		this.addressPostalcode = addressPostalcode;
	}

	public String getUserPreferences() {
		return this.userPreferences;
	}

	public void setUserPreferences(String userPreferences) {
		this.userPreferences = userPreferences;
	}

	public String getTz() {
		return this.tz;
	}

	public void setTz(String tz) {
		this.tz = tz;
	}

	public String getHolidays() {
		return this.holidays;
	}

	public void setHolidays(String holidays) {
		this.holidays = holidays;
	}

	public String getNamedays() {
		return this.namedays;
	}

	public void setNamedays(String namedays) {
		this.namedays = namedays;
	}

	public String getWorkdays() {
		return this.workdays;
	}

	public void setWorkdays(String workdays) {
		this.workdays = workdays;
	}

	public Integer getWeekstart() {
		return this.weekstart;
	}

	public void setWeekstart(Integer weekstart) {
		this.weekstart = weekstart;
	}

	public String getDateFormat() {
		return this.dateFormat;
	}

	public void setDateFormat(String dateFormat) {
		this.dateFormat = dateFormat;
	}

	public String getHourFormat() {
		return this.hourFormat;
	}

	public void setHourFormat(String hourFormat) {
		this.hourFormat = hourFormat;
	}

	public String getStartHour() {
		return this.startHour;
	}

	public void setStartHour(String startHour) {
		this.startHour = startHour;
	}

	public String getEndHour() {
		return this.endHour;
	}

	public void setEndHour(String endHour) {
		this.endHour = endHour;
	}

	public String getActivityView() {
		return this.activityView;
	}

	public void setActivityView(String activityView) {
		this.activityView = activityView;
	}

	public String getLeadView() {
		return this.leadView;
	}

	public void setLeadView(String leadView) {
		this.leadView = leadView;
	}

	public String getImagename() {
		return this.imagename;
	}

	public void setImagename(String imagename) {
		this.imagename = imagename;
	}

	public int getDeleted() {
		return this.deleted;
	}

	public void setDeleted(int deleted) {
		this.deleted = deleted;
	}

	public String getConfirmPassword() {
		return this.confirmPassword;
	}

	public void setConfirmPassword(String confirmPassword) {
		this.confirmPassword = confirmPassword;
	}

	public String getInternalMailer() {
		return this.internalMailer;
	}

	public void setInternalMailer(String internalMailer) {
		this.internalMailer = internalMailer;
	}

	public String getReminderInterval() {
		return this.reminderInterval;
	}

	public void setReminderInterval(String reminderInterval) {
		this.reminderInterval = reminderInterval;
	}

	public String getReminderNextTime() {
		return this.reminderNextTime;
	}

	public void setReminderNextTime(String reminderNextTime) {
		this.reminderNextTime = reminderNextTime;
	}

	public String getCryptType() {
		return this.cryptType;
	}

	public void setCryptType(String cryptType) {
		this.cryptType = cryptType;
	}

	public String getAccesskey() {
		return this.accesskey;
	}

	public void setAccesskey(String accesskey) {
		this.accesskey = accesskey;
	}

}
